--------------------------------------------------------------------------------
-- CTELL · DDL DE PERMISOS
--
-- Crea las tablas que necesita db/paginas.sql. Se ejecuta UNA SOLA VEZ, ANTES
-- de ese archivo: sin estas tablas el paquete PKG_PERMISOS no compila y falla
-- con ORA-00942 ("la tabla o vista no existe").
--
-- A diferencia del resto de db/, este archivo SÍ crea y altera tablas — por
-- eso está separado. Los scripts de negocio asumen que el DDL ya corrió.
--
-- NO es idempotente: reejecutarlo da ORA-00955 ("nombre ya utilizado"). Si
-- necesitás empezar de cero, mirá el bloque comentado del final.
--
-- Orden correcto:
--   1. db/ddl-permisos.sql   ← este archivo, una sola vez
--   2. db/paginas.sql         ← paquete + endpoints, reejecutable
--------------------------------------------------------------------------------

-- Nivel 1: agrupador del menú. No se permite ni se niega; se muestra si el
-- usuario tiene al menos una página adentro.
CREATE TABLE MODULOS (
  ID_MODULO NUMBER GENERATED BY DEFAULT AS IDENTITY MINVALUE 1 INCREMENT BY 1
            START WITH 1 CACHE 20 NOORDER NOCYCLE NOT NULL ENABLE,
  CODIGO    VARCHAR2(30)  NOT NULL ENABLE,
  NOMBRE    VARCHAR2(100) NOT NULL ENABLE,
  ICONO     VARCHAR2(50),
  ORDEN     NUMBER DEFAULT 0,
  ACTIVO    VARCHAR2(1) DEFAULT 'A',
  PRIMARY KEY (ID_MODULO) USING INDEX ENABLE,
  UNIQUE (CODIGO) USING INDEX ENABLE
);

-- Nivel 2: la página concreta. ESTO es lo que se permite.
CREATE TABLE PAGINAS (
  ID_PAGINA NUMBER GENERATED BY DEFAULT AS IDENTITY MINVALUE 1 INCREMENT BY 1
            START WITH 1 CACHE 20 NOORDER NOCYCLE NOT NULL ENABLE,
  ID_MODULO NUMBER        NOT NULL ENABLE,
  CODIGO    VARCHAR2(50)  NOT NULL ENABLE,
  NOMBRE    VARCHAR2(100) NOT NULL ENABLE,
  RUTA      VARCHAR2(150) NOT NULL ENABLE,
  ORDEN     NUMBER DEFAULT 0,
  ACTIVO    VARCHAR2(1) DEFAULT 'A',
  PRIMARY KEY (ID_PAGINA) USING INDEX ENABLE,
  UNIQUE (CODIGO) USING INDEX ENABLE,
  -- Dos páginas con la misma URL harían que el permiso dependiera de cuál se
  -- consultó primero.
  UNIQUE (RUTA) USING INDEX ENABLE
);

-- Sin ON DELETE CASCADE: borrar un módulo con páginas debe fallar, no
-- llevarse las páginas y sus permisos en silencio.
ALTER TABLE PAGINAS ADD CONSTRAINT FK_PAGINA_MODULO
  FOREIGN KEY (ID_MODULO) REFERENCES MODULOS (ID_MODULO) ENABLE;

-- Qué usuario entra a qué página. La ausencia de fila es la negación.
CREATE TABLE USUARIO_PAGINAS (
  ID_USUARIO NUMBER NOT NULL ENABLE,
  ID_PAGINA  NUMBER NOT NULL ENABLE,
  FECHA_ALTA TIMESTAMP(6) DEFAULT SYSTIMESTAMP,
  -- Clave compuesta y sin ID propio: impide otorgar el mismo permiso dos
  -- veces, que dejaría una fila viva al revocar.
  PRIMARY KEY (ID_USUARIO, ID_PAGINA) USING INDEX ENABLE
);

-- Acá sí va CASCADE: eliminar un usuario debe limpiar sus permisos, como pasa
-- con TOKENS. Sin esto, ELIMINAR_USUARIO falla por la FK.
ALTER TABLE USUARIO_PAGINAS ADD CONSTRAINT FK_UP_USUARIO
  FOREIGN KEY (ID_USUARIO) REFERENCES USUARIOS (ID_USUARIO) ON DELETE CASCADE ENABLE;

ALTER TABLE USUARIO_PAGINAS ADD CONSTRAINT FK_UP_PAGINA
  FOREIGN KEY (ID_PAGINA) REFERENCES PAGINAS (ID_PAGINA) ON DELETE CASCADE ENABLE;

-- La PK ya cubre las consultas por usuario, pero el filtro por página
-- (¿quiénes acceden a Cobranzas?) haría full scan sin este índice.
CREATE INDEX IDX_UP_PAGINA ON USUARIO_PAGINAS (ID_PAGINA);

-- Listar las páginas de un módulo es la consulta más frecuente del menú.
CREATE INDEX IDX_PAGINA_MODULO ON PAGINAS (ID_MODULO, ORDEN);

-- Quién administra permisos. 'S' = sí, 'N' = no. Un admin ve todo sin
-- necesitar filas en USUARIO_PAGINAS: sin esto, un error al asignar permisos
-- dejaría al sistema sin nadie capaz de corregirlo.
ALTER TABLE USUARIOS ADD (ES_ADMIN VARCHAR2(1) DEFAULT 'N');

-- El admin inicial tiene que poder asignar permisos desde el arranque.
UPDATE USUARIOS SET ES_ADMIN = 'S' WHERE USUARIO = 'admin';

COMMIT;

--------------------------------------------------------------------------------
-- VERIFICACIÓN
--------------------------------------------------------------------------------

-- Las tres tablas tienen que aparecer acá.
SELECT TABLE_NAME
  FROM USER_TABLES
 WHERE TABLE_NAME IN ('MODULOS', 'PAGINAS', 'USUARIO_PAGINAS')
 ORDER BY TABLE_NAME;

-- Y la columna nueva sobre USUARIOS.
SELECT COLUMN_NAME, DATA_TYPE, DATA_DEFAULT
  FROM USER_TAB_COLUMNS
 WHERE TABLE_NAME = 'USUARIOS'
   AND COLUMN_NAME = 'ES_ADMIN';

-- El admin quedó marcado.
SELECT USUARIO, ES_ADMIN FROM USUARIOS WHERE USUARIO = 'admin';

--------------------------------------------------------------------------------
-- REINICIO (solo si necesitás empezar de cero)
--
-- Borra las tres tablas y sus datos, permisos incluidos. El orden importa:
-- las hijas primero, o las FK abortan el DROP.
--------------------------------------------------------------------------------

/*
DROP TABLE USUARIO_PAGINAS CASCADE CONSTRAINTS;
DROP TABLE PAGINAS CASCADE CONSTRAINTS;
DROP TABLE MODULOS CASCADE CONSTRAINTS;
ALTER TABLE USUARIOS DROP COLUMN ES_ADMIN;
COMMIT;
*/
