--------------------------------------------------------------------------------
-- CTELL · MODULOS, PAGINAS Y PERMISOS POR USUARIO
--
-- Script único: paquete PL/SQL + endpoints ORDS. Se ejecuta de una sola vez
-- en la hoja de trabajo SQL de APEX, conectado con el esquema del workspace.
--
-- Contenido:
--   0. DDL de referencia  — comentado, se ejecuta APARTE (ver nota)
--   1. PKG_PERMISOS       — módulos, páginas y asignación por usuario
--   2. ORDS /modulos/     — catálogo de módulos (ABM)
--   3. ORDS /paginas/     — catálogo de páginas (ABM)
--   4. ORDS /permisos/    — qué páginas ve cada usuario
--   5. Datos iniciales    — módulo Ventas y sus páginas
--   6. Verificación
--
-- Base de los endpoints: https://oracleapex.com/ords/ctell/
--
-- MODELO DE PERMISOS · dos niveles
--
--   Ventas (MODULO)              ← agrupa, se ve en el menú lateral
--   ├── Clientes (PAGINA)        ← esto es lo que se permite
--   ├── Límites de crédito
--   ├── Facturación
--   └── Cobranzas
--
-- El permiso va sobre la PÁGINA, nunca sobre el módulo. Un módulo aparece en
-- el menú si el usuario tiene al menos una de sus páginas: así no puede haber
-- un menú que no lleva a ninguna parte, ni una página accesible cuyo módulo
-- esté oculto. Por eso no existe una tabla USUARIO_MODULOS.
--
-- La ausencia de fila en USUARIO_PAGINAS es la negación. No hay columna
-- PUEDE_VER con 1/0: un permiso está o no está. Guardar negaciones explícitas
-- abre la pregunta de cuál gana si existieran ambas.
--
-- USUARIOS.ES_ADMIN corta por lo sano: un admin ve todo sin necesitar filas.
-- Sin eso, un error al asignar permisos dejaría al sistema sin nadie capaz de
-- corregirlo.
--
-- ESTADO: la columna ACTIVO usa 'A' (activo) / 'I' (inactivo), igual que
-- USUARIOS. Ver la nota extensa en db/usuarios.sql: compararla contra un
-- número la rompe con ORA-01722.
--------------------------------------------------------------------------------

SET DEFINE OFF
SET SERVEROUTPUT ON

--------------------------------------------------------------------------------
-- 0. REQUISITO PREVIO · EJECUTAR db/ddl-permisos.sql PRIMERO
--
--   >>> Este script NO crea tablas. Si MODULOS, PAGINAS y USUARIO_PAGINAS no
--   >>> existen todavía, PKG_PERMISOS no compila y todo falla con
--   >>> ORA-00942 ("la tabla o vista no existe").
--
-- Orden correcto:
--   1. db/ddl-permisos.sql   una sola vez (crea tablas, índices y ES_ADMIN)
--   2. db/paginas.sql        este archivo, reejecutable
--
-- El DDL vive aparte porque el resto de db/ no crea ni altera tablas. Abajo
-- queda una copia como referencia de lo que ese archivo hace.
--------------------------------------------------------------------------------

/*
-- Nivel 1: agrupador del menú. No se permite ni se niega.
CREATE TABLE MODULOS (
  ID_MODULO NUMBER GENERATED BY DEFAULT AS IDENTITY MINVALUE 1 INCREMENT BY 1
            START WITH 1 CACHE 20 NOORDER NOCYCLE NOT NULL ENABLE,
  CODIGO    VARCHAR2(30)  NOT NULL ENABLE,
  NOMBRE    VARCHAR2(100) NOT NULL ENABLE,
  ICONO     VARCHAR2(50),
  ORDEN     NUMBER DEFAULT 0,
  ACTIVO    VARCHAR2(1) DEFAULT 'A',
  PRIMARY KEY (ID_MODULO) USING INDEX ENABLE,
  UNIQUE (CODIGO) USING INDEX ENABLE
);

-- Nivel 2: la página concreta. ESTO es lo que se permite.
CREATE TABLE PAGINAS (
  ID_PAGINA NUMBER GENERATED BY DEFAULT AS IDENTITY MINVALUE 1 INCREMENT BY 1
            START WITH 1 CACHE 20 NOORDER NOCYCLE NOT NULL ENABLE,
  ID_MODULO NUMBER        NOT NULL ENABLE,
  CODIGO    VARCHAR2(50)  NOT NULL ENABLE,
  NOMBRE    VARCHAR2(100) NOT NULL ENABLE,
  RUTA      VARCHAR2(150) NOT NULL ENABLE,
  ORDEN     NUMBER DEFAULT 0,
  ACTIVO    VARCHAR2(1) DEFAULT 'A',
  PRIMARY KEY (ID_PAGINA) USING INDEX ENABLE,
  UNIQUE (CODIGO) USING INDEX ENABLE,
  -- Dos páginas con la misma URL harían que el permiso dependiera de cuál se
  -- consultó primero.
  UNIQUE (RUTA) USING INDEX ENABLE
);

-- Sin ON DELETE CASCADE: borrar un módulo con páginas debe fallar, no
-- llevarse las páginas y sus permisos en silencio.
ALTER TABLE PAGINAS ADD CONSTRAINT FK_PAGINA_MODULO
  FOREIGN KEY (ID_MODULO) REFERENCES MODULOS (ID_MODULO) ENABLE;

-- Qué usuario entra a qué página.
CREATE TABLE USUARIO_PAGINAS (
  ID_USUARIO NUMBER NOT NULL ENABLE,
  ID_PAGINA  NUMBER NOT NULL ENABLE,
  FECHA_ALTA TIMESTAMP(6) DEFAULT SYSTIMESTAMP,
  -- Clave compuesta y sin ID propio: impide otorgar el mismo permiso dos
  -- veces, que dejaría una fila viva al revocar.
  PRIMARY KEY (ID_USUARIO, ID_PAGINA) USING INDEX ENABLE
);

-- Acá sí va CASCADE: eliminar un usuario debe limpiar sus permisos, como pasa
-- con TOKENS. Sin esto, ELIMINAR_USUARIO falla por la FK.
ALTER TABLE USUARIO_PAGINAS ADD CONSTRAINT FK_UP_USUARIO
  FOREIGN KEY (ID_USUARIO) REFERENCES USUARIOS (ID_USUARIO) ON DELETE CASCADE ENABLE;

ALTER TABLE USUARIO_PAGINAS ADD CONSTRAINT FK_UP_PAGINA
  FOREIGN KEY (ID_PAGINA) REFERENCES PAGINAS (ID_PAGINA) ON DELETE CASCADE ENABLE;

-- La PK ya cubre las consultas por usuario, pero el filtro por página
-- (¿quiénes acceden a Cobranzas?) haría full scan sin este índice.
CREATE INDEX IDX_UP_PAGINA ON USUARIO_PAGINAS (ID_PAGINA);

-- Listar las páginas de un módulo es la consulta más frecuente del menú.
CREATE INDEX IDX_PAGINA_MODULO ON PAGINAS (ID_MODULO, ORDEN);

-- Quién administra permisos. 'S' = sí, 'N' = no.
ALTER TABLE USUARIOS ADD (ES_ADMIN VARCHAR2(1) DEFAULT 'N');

-- El admin inicial tiene que poder asignar permisos desde el arranque.
UPDATE USUARIOS SET ES_ADMIN = 'S' WHERE USUARIO = 'admin';
COMMIT;
*/

--------------------------------------------------------------------------------
-- 1. PKG_PERMISOS
--------------------------------------------------------------------------------

CREATE OR REPLACE PACKAGE PKG_PERMISOS AS

  -- Mismo rango de errores de negocio que PKG_USUARIOS: los handlers los
  -- traducen igual a 400/404.
  C_ERR_DUPLICADO CONSTANT PLS_INTEGER := -20001;
  C_ERR_NO_EXISTE CONSTANT PLS_INTEGER := -20002;
  C_ERR_EN_USO    CONSTANT PLS_INTEGER := -20003;
  C_ERR_DATOS     CONSTANT PLS_INTEGER := -20004;

  C_ESTADO_ACTIVO   CONSTANT VARCHAR2(1) := 'A';
  C_ESTADO_INACTIVO CONSTANT VARCHAR2(1) := 'I';

  ------------------------------------------------------------------ MODULOS --

  PROCEDURE CREAR_MODULO (
    p_codigo    IN  VARCHAR2,
    p_nombre    IN  VARCHAR2,
    p_icono     IN  VARCHAR2 DEFAULT NULL,
    p_orden     IN  NUMBER   DEFAULT 0,
    p_id_modulo OUT NUMBER
  );

  PROCEDURE ACTUALIZAR_MODULO (
    p_id_modulo IN NUMBER,
    p_nombre    IN VARCHAR2 DEFAULT NULL,
    p_icono     IN VARCHAR2 DEFAULT NULL,
    p_orden     IN NUMBER   DEFAULT NULL,
    p_activo    IN VARCHAR2 DEFAULT NULL
  );

  PROCEDURE ELIMINAR_MODULO (p_id_modulo IN NUMBER);

  ------------------------------------------------------------------ PAGINAS --

  PROCEDURE CREAR_PAGINA (
    p_id_modulo IN  NUMBER,
    p_codigo    IN  VARCHAR2,
    p_nombre    IN  VARCHAR2,
    p_ruta      IN  VARCHAR2,
    p_orden     IN  NUMBER DEFAULT 0,
    p_id_pagina OUT NUMBER
  );

  PROCEDURE ACTUALIZAR_PAGINA (
    p_id_pagina IN NUMBER,
    p_id_modulo IN NUMBER   DEFAULT NULL,
    p_nombre    IN VARCHAR2 DEFAULT NULL,
    p_ruta      IN VARCHAR2 DEFAULT NULL,
    p_orden     IN NUMBER   DEFAULT NULL,
    p_activo    IN VARCHAR2 DEFAULT NULL
  );

  PROCEDURE ELIMINAR_PAGINA (p_id_pagina IN NUMBER);

  ----------------------------------------------------------------- PERMISOS --

  -- Otorgar es idempotente: repetirlo no duplica ni falla.
  PROCEDURE OTORGAR (p_id_usuario IN NUMBER, p_id_pagina IN NUMBER);
  PROCEDURE REVOCAR (p_id_usuario IN NUMBER, p_id_pagina IN NUMBER);

  -- Reemplaza TODOS los permisos del usuario por la lista recibida (IDs
  -- separados por coma). Es lo que usa la UI al guardar la selección.
  PROCEDURE REEMPLAZAR (p_id_usuario IN NUMBER, p_ids_paginas IN VARCHAR2);

  -- TRUE si el usuario puede entrar. Un admin siempre puede.
  FUNCTION PUEDE_ACCEDER (
    p_id_usuario IN NUMBER,
    p_ruta       IN VARCHAR2
  ) RETURN BOOLEAN;

  FUNCTION ES_ADMIN (p_id_usuario IN NUMBER) RETURN BOOLEAN;

END PKG_PERMISOS;
/

CREATE OR REPLACE PACKAGE BODY PKG_PERMISOS AS

  --------------------------------------------------------------------------
  -- Privados
  --------------------------------------------------------------------------

  -- NOTA · la traducción 1/0 -> 'A'/'I' va como CASE inline en cada UPDATE,
  -- no como función auxiliar. Una función privada de paquete no se puede
  -- invocar desde SQL: hacerlo da PLS-00231 y el cuerpo entero no compila.
  -- Lo mismo vale para los JSON_OBJECT de los handlers, que usan CASE.

  PROCEDURE VALIDAR_RUTA (p_ruta IN VARCHAR2) IS
  BEGIN
    -- La ruta tiene que existir en src/routes/ del frontend. Se valida el
    -- formato, no la existencia: la base no puede saber qué rutas hay.
    IF p_ruta IS NULL OR NOT REGEXP_LIKE(p_ruta, '^/[a-z0-9/_-]*$') THEN
      RAISE_APPLICATION_ERROR(C_ERR_DATOS,
        'La ruta debe empezar con / y usar solo minusculas, numeros, guion y barra');
    END IF;
  END VALIDAR_RUTA;

  --------------------------------------------------------------------------
  -- Modulos
  --------------------------------------------------------------------------

  PROCEDURE CREAR_MODULO (
    p_codigo    IN  VARCHAR2,
    p_nombre    IN  VARCHAR2,
    p_icono     IN  VARCHAR2 DEFAULT NULL,
    p_orden     IN  NUMBER   DEFAULT 0,
    p_id_modulo OUT NUMBER
  ) IS
    l_codigo VARCHAR2(30) := UPPER(TRIM(p_codigo));
  BEGIN
    IF l_codigo IS NULL OR LENGTH(l_codigo) < 2 THEN
      RAISE_APPLICATION_ERROR(C_ERR_DATOS, 'El codigo es obligatorio');
    END IF;

    IF TRIM(p_nombre) IS NULL THEN
      RAISE_APPLICATION_ERROR(C_ERR_DATOS, 'El nombre es obligatorio');
    END IF;

    INSERT INTO MODULOS (CODIGO, NOMBRE, ICONO, ORDEN, ACTIVO)
    VALUES (l_codigo, TRIM(p_nombre), TRIM(p_icono), NVL(p_orden, 0), C_ESTADO_ACTIVO)
    RETURNING ID_MODULO INTO p_id_modulo;

  EXCEPTION
    WHEN DUP_VAL_ON_INDEX THEN
      RAISE_APPLICATION_ERROR(C_ERR_DUPLICADO, 'Ya existe un modulo con ese codigo');
  END CREAR_MODULO;

  PROCEDURE ACTUALIZAR_MODULO (
    p_id_modulo IN NUMBER,
    p_nombre    IN VARCHAR2 DEFAULT NULL,
    p_icono     IN VARCHAR2 DEFAULT NULL,
    p_orden     IN NUMBER   DEFAULT NULL,
    p_activo    IN VARCHAR2 DEFAULT NULL
  ) IS
  BEGIN
    -- El CODIGO no se actualiza: es la referencia estable que usa el resto
    -- del sistema. Para cambiarlo, se crea otro módulo.
    UPDATE MODULOS
       SET NOMBRE = NVL(TRIM(p_nombre), NOMBRE),
           ICONO  = NVL(TRIM(p_icono), ICONO),
           ORDEN  = NVL(p_orden, ORDEN),
           -- p_activo ya es el codigo de la columna: 'A' o 'I'. NULL conserva
           -- el valor actual, y un valor invalido tambien: es preferible
           -- ignorarlo a escribir basura en la columna.
           ACTIVO = CASE UPPER(TRIM(p_activo))
                      WHEN C_ESTADO_ACTIVO   THEN C_ESTADO_ACTIVO
                      WHEN C_ESTADO_INACTIVO THEN C_ESTADO_INACTIVO
                      ELSE ACTIVO
                    END
     WHERE ID_MODULO = p_id_modulo;

    IF SQL%ROWCOUNT = 0 THEN
      RAISE_APPLICATION_ERROR(C_ERR_NO_EXISTE, 'El modulo no existe');
    END IF;
  END ACTUALIZAR_MODULO;

  PROCEDURE ELIMINAR_MODULO (p_id_modulo IN NUMBER) IS
    l_paginas NUMBER;
  BEGIN
    -- La FK ya lo impediría, pero el mensaje de Oracle no explica nada al
    -- usuario. Se chequea antes para devolver algo entendible.
    SELECT COUNT(*) INTO l_paginas FROM PAGINAS WHERE ID_MODULO = p_id_modulo;

    IF l_paginas > 0 THEN
      RAISE_APPLICATION_ERROR(C_ERR_EN_USO,
        'El modulo tiene ' || l_paginas || ' pagina(s): eliminalas primero');
    END IF;

    DELETE FROM MODULOS WHERE ID_MODULO = p_id_modulo;

    IF SQL%ROWCOUNT = 0 THEN
      RAISE_APPLICATION_ERROR(C_ERR_NO_EXISTE, 'El modulo no existe');
    END IF;
  END ELIMINAR_MODULO;

  --------------------------------------------------------------------------
  -- Paginas
  --------------------------------------------------------------------------

  PROCEDURE CREAR_PAGINA (
    p_id_modulo IN  NUMBER,
    p_codigo    IN  VARCHAR2,
    p_nombre    IN  VARCHAR2,
    p_ruta      IN  VARCHAR2,
    p_orden     IN  NUMBER DEFAULT 0,
    p_id_pagina OUT NUMBER
  ) IS
    l_codigo VARCHAR2(50) := UPPER(TRIM(p_codigo));
    l_existe NUMBER;
  BEGIN
    IF l_codigo IS NULL OR LENGTH(l_codigo) < 2 THEN
      RAISE_APPLICATION_ERROR(C_ERR_DATOS, 'El codigo es obligatorio');
    END IF;

    IF TRIM(p_nombre) IS NULL THEN
      RAISE_APPLICATION_ERROR(C_ERR_DATOS, 'El nombre es obligatorio');
    END IF;

    VALIDAR_RUTA(p_ruta);

    SELECT COUNT(*) INTO l_existe FROM MODULOS WHERE ID_MODULO = p_id_modulo;
    IF l_existe = 0 THEN
      RAISE_APPLICATION_ERROR(C_ERR_NO_EXISTE, 'El modulo no existe');
    END IF;

    INSERT INTO PAGINAS (ID_MODULO, CODIGO, NOMBRE, RUTA, ORDEN, ACTIVO)
    VALUES (p_id_modulo, l_codigo, TRIM(p_nombre), LOWER(TRIM(p_ruta)),
            NVL(p_orden, 0), C_ESTADO_ACTIVO)
    RETURNING ID_PAGINA INTO p_id_pagina;

  EXCEPTION
    WHEN DUP_VAL_ON_INDEX THEN
      RAISE_APPLICATION_ERROR(C_ERR_DUPLICADO,
        'Ya existe una pagina con ese codigo o esa ruta');
  END CREAR_PAGINA;

  PROCEDURE ACTUALIZAR_PAGINA (
    p_id_pagina IN NUMBER,
    p_id_modulo IN NUMBER   DEFAULT NULL,
    p_nombre    IN VARCHAR2 DEFAULT NULL,
    p_ruta      IN VARCHAR2 DEFAULT NULL,
    p_orden     IN NUMBER   DEFAULT NULL,
    p_activo    IN VARCHAR2 DEFAULT NULL
  ) IS
  BEGIN
    IF p_ruta IS NOT NULL THEN
      VALIDAR_RUTA(p_ruta);
    END IF;

    UPDATE PAGINAS
       SET ID_MODULO = NVL(p_id_modulo, ID_MODULO),
           NOMBRE    = NVL(TRIM(p_nombre), NOMBRE),
           RUTA      = NVL(LOWER(TRIM(p_ruta)), RUTA),
           ORDEN     = NVL(p_orden, ORDEN),
           -- 'A'/'I'; ver la nota en ACTUALIZAR_MODULO.
           ACTIVO    = CASE UPPER(TRIM(p_activo))
                         WHEN C_ESTADO_ACTIVO   THEN C_ESTADO_ACTIVO
                         WHEN C_ESTADO_INACTIVO THEN C_ESTADO_INACTIVO
                         ELSE ACTIVO
                       END
     WHERE ID_PAGINA = p_id_pagina;

    IF SQL%ROWCOUNT = 0 THEN
      RAISE_APPLICATION_ERROR(C_ERR_NO_EXISTE, 'La pagina no existe');
    END IF;

  EXCEPTION
    WHEN DUP_VAL_ON_INDEX THEN
      RAISE_APPLICATION_ERROR(C_ERR_DUPLICADO, 'Ya existe otra pagina con esa ruta');
  END ACTUALIZAR_PAGINA;

  PROCEDURE ELIMINAR_PAGINA (p_id_pagina IN NUMBER) IS
  BEGIN
    -- Los permisos caen por el ON DELETE CASCADE de USUARIO_PAGINAS.
    DELETE FROM PAGINAS WHERE ID_PAGINA = p_id_pagina;

    IF SQL%ROWCOUNT = 0 THEN
      RAISE_APPLICATION_ERROR(C_ERR_NO_EXISTE, 'La pagina no existe');
    END IF;
  END ELIMINAR_PAGINA;

  --------------------------------------------------------------------------
  -- Permisos
  --------------------------------------------------------------------------

  PROCEDURE OTORGAR (p_id_usuario IN NUMBER, p_id_pagina IN NUMBER) IS
  BEGIN
    INSERT INTO USUARIO_PAGINAS (ID_USUARIO, ID_PAGINA)
    VALUES (p_id_usuario, p_id_pagina);
  EXCEPTION
    WHEN DUP_VAL_ON_INDEX THEN
      -- Ya lo tenía: otorgar dos veces es un no-op, no un error.
      NULL;
  END OTORGAR;

  PROCEDURE REVOCAR (p_id_usuario IN NUMBER, p_id_pagina IN NUMBER) IS
  BEGIN
    DELETE FROM USUARIO_PAGINAS
     WHERE ID_USUARIO = p_id_usuario
       AND ID_PAGINA  = p_id_pagina;
    -- Sin error si no existía: revocar es idempotente.
  END REVOCAR;

  PROCEDURE REEMPLAZAR (p_id_usuario IN NUMBER, p_ids_paginas IN VARCHAR2) IS
    l_existe NUMBER;
  BEGIN
    SELECT COUNT(*) INTO l_existe FROM USUARIOS WHERE ID_USUARIO = p_id_usuario;
    IF l_existe = 0 THEN
      RAISE_APPLICATION_ERROR(C_ERR_NO_EXISTE, 'El usuario no existe');
    END IF;

    -- Borrar e insertar dentro de la misma transacción: si algo falla, el
    -- ROLLBACK del handler deja los permisos como estaban. Nunca queda a
    -- medias con el usuario sin acceso a nada.
    DELETE FROM USUARIO_PAGINAS WHERE ID_USUARIO = p_id_usuario;

    IF p_ids_paginas IS NOT NULL AND TRIM(p_ids_paginas) IS NOT NULL THEN
      INSERT INTO USUARIO_PAGINAS (ID_USUARIO, ID_PAGINA)
      SELECT p_id_usuario, TO_NUMBER(COLUMN_VALUE)
        FROM XMLTABLE(('"' || REPLACE(p_ids_paginas, ',', '","') || '"'))
       WHERE TO_NUMBER(COLUMN_VALUE) IN (SELECT ID_PAGINA FROM PAGINAS);
      -- El IN filtra IDs inexistentes en vez de abortar: la UI podría mandar
      -- una página borrada por otro usuario mientras editaba.
    END IF;
  END REEMPLAZAR;

  FUNCTION ES_ADMIN (p_id_usuario IN NUMBER) RETURN BOOLEAN IS
    l_admin VARCHAR2(1);
  BEGIN
    SELECT UPPER(TRIM(ES_ADMIN)) INTO l_admin
      FROM USUARIOS
     WHERE ID_USUARIO = p_id_usuario;

    RETURN l_admin = 'S';
  EXCEPTION
    WHEN NO_DATA_FOUND THEN
      RETURN FALSE;
  END ES_ADMIN;

  FUNCTION PUEDE_ACCEDER (
    p_id_usuario IN NUMBER,
    p_ruta       IN VARCHAR2
  ) RETURN BOOLEAN IS
    l_cuenta NUMBER;
  BEGIN
    -- El admin entra a todo sin filas en USUARIO_PAGINAS.
    IF ES_ADMIN(p_id_usuario) THEN
      RETURN TRUE;
    END IF;

    SELECT COUNT(*)
      INTO l_cuenta
      FROM USUARIO_PAGINAS up
      JOIN PAGINAS p ON p.ID_PAGINA = up.ID_PAGINA
      JOIN MODULOS m ON m.ID_MODULO = p.ID_MODULO
     WHERE up.ID_USUARIO = p_id_usuario
       AND p.RUTA = LOWER(TRIM(p_ruta))
       -- Inactivar el módulo corta el acceso a sus páginas sin tener que
       -- revocar permiso por permiso.
       AND UPPER(TRIM(p.ACTIVO)) = C_ESTADO_ACTIVO
       AND UPPER(TRIM(m.ACTIVO)) = C_ESTADO_ACTIVO;

    RETURN l_cuenta > 0;
  END PUEDE_ACCEDER;

END PKG_PERMISOS;
/

--------------------------------------------------------------------------------
-- 2. ORDS · MÓDULO /modulos/   (requieren token)
--
--   GET    /modulos/       listado con sus páginas
--   POST   /modulos/       alta
--   PUT    /modulos/:id    modificación
--   DELETE /modulos/:id    baja
--------------------------------------------------------------------------------

--------------------------------------------------------------------------------
-- Borra un módulo ORDS si existe, reintentando ante un interbloqueo.
--
-- Copia del que también define db/usuarios.sql: cada archivo se ejecuta por
-- separado y no puede asumir que el otro ya corrió. `CREATE OR REPLACE` hace
-- que redefinirlo sea inocuo.
--
-- Un `WHEN OTHERS THEN NULL` acá se tragaba el ORA-00060 del interbloqueo: el
-- DELETE fallaba en silencio y el DEFINE_MODULE moría después con ORA-00001
-- por nombre duplicado. El interbloqueo aparece cuando otra sesión tiene
-- tomadas las filas de metadatos de ORDS —el propio ORDS sirviendo peticiones
-- mientras se reejecuta el script—, es transitorio y se reintenta.
--------------------------------------------------------------------------------
CREATE OR REPLACE PROCEDURE BORRAR_MODULO_ORDS (p_modulo IN VARCHAR2) AS
  C_INTENTOS CONSTANT PLS_INTEGER := 3;
  l_existe   PLS_INTEGER;
BEGIN
  FOR i IN 1 .. C_INTENTOS LOOP
    BEGIN
      SELECT COUNT(*)
        INTO l_existe
        FROM USER_ORDS_MODULES
       WHERE NAME = p_modulo;

      IF l_existe = 0 THEN
        RETURN;
      END IF;

      ORDS.DELETE_MODULE(p_module_name => p_modulo);
      COMMIT;
      RETURN;

    EXCEPTION
      WHEN OTHERS THEN
        IF SQLCODE IN (-60, -4020) AND i < C_INTENTOS THEN
          ROLLBACK;
          DBMS_SESSION.SLEEP(2);
        ELSE
          RAISE;
        END IF;
    END;
  END LOOP;
END BORRAR_MODULO_ORDS;
/

BEGIN
  BORRAR_MODULO_ORDS('modulos');

  ORDS.DEFINE_MODULE(
    p_module_name    => 'modulos',
    p_base_path      => '/modulos/',
    p_items_per_page => 0,
    p_status         => 'PUBLISHED',
    p_comments       => 'Catalogo de modulos (requiere token)'
  );

  ----------------------------------------------------------------------------
  -- GET /modulos/  · catálogo completo, con las páginas de cada módulo
  ----------------------------------------------------------------------------
  ORDS.DEFINE_TEMPLATE(p_module_name => 'modulos', p_pattern => '.');

  ORDS.DEFINE_HANDLER(
    p_module_name => 'modulos',
    p_pattern     => '.',
    p_method      => 'GET',
    p_source_type => ORDS.source_type_plsql,
    p_source      => q'~
DECLARE
  l_sesion NUMBER;
  l_items  CLOB;
BEGIN
  l_sesion := PKG_TOKENS.VALIDAR_TOKEN(REPLACE(:authorization, 'Bearer ', ''));
  IF l_sesion IS NULL THEN
    :status_code := 401;
    :resultado := '{"error":"Sesion invalida o vencida"}';
    RETURN;
  END IF;

  SELECT JSON_ARRAYAGG(
           JSON_OBJECT(
             'id'      VALUE m.ID_MODULO,
             'codigo'  VALUE m.CODIGO,
             'nombre'  VALUE m.NOMBRE,
             'icono'   VALUE m.ICONO,
             'orden'   VALUE m.ORDEN,
             -- 'A'/'I' tal cual la columna, sin traducir a numeros.
             'activo'  VALUE UPPER(TRIM(m.ACTIVO)),
             'paginas' VALUE (
               SELECT JSON_ARRAYAGG(
                        JSON_OBJECT(
                          'id'     VALUE p.ID_PAGINA,
                          'codigo' VALUE p.CODIGO,
                          'nombre' VALUE p.NOMBRE,
                          'ruta'   VALUE p.RUTA,
                          'orden'  VALUE p.ORDEN,
                          'activo' VALUE UPPER(TRIM(p.ACTIVO))
                          RETURNING CLOB
                        ) ORDER BY p.ORDEN, p.NOMBRE RETURNING CLOB
                      )
                 FROM PAGINAS p
                WHERE p.ID_MODULO = m.ID_MODULO
             ) FORMAT JSON
             RETURNING CLOB
           ) ORDER BY m.ORDEN, m.NOMBRE RETURNING CLOB
         )
    INTO l_items
    FROM MODULOS m;

  :status_code := 200;
  -- NVL sobre el agregado: sin módulos, JSON_ARRAYAGG devuelve NULL y el
  -- cliente recibiria "null" en vez de una lista vacia.
  :resultado := JSON_OBJECT('items' VALUE NVL(l_items, TO_CLOB('[]')) FORMAT JSON
                            RETURNING CLOB);
EXCEPTION
  WHEN OTHERS THEN
    APEX_DEBUG.ERROR('modulos GET: ' || SQLERRM || ' | ' ||
                     DBMS_UTILITY.FORMAT_ERROR_BACKTRACE);
    :status_code := 500;
    :resultado := '{"error":"Error al listar modulos"}';
END;
~'
  );

  ORDS.DEFINE_PARAMETER(
    p_module_name => 'modulos', p_pattern => '.', p_method => 'GET',
    p_name => 'authorization', p_bind_variable_name => 'authorization',
    p_source_type => 'HEADER', p_param_type => 'STRING', p_access_method => 'IN');

  ORDS.DEFINE_PARAMETER(
    p_module_name => 'modulos', p_pattern => '.', p_method => 'GET',
    p_name => 'resultado', p_bind_variable_name => 'resultado',
    p_source_type => 'RESPONSE', p_param_type => 'STRING', p_access_method => 'OUT');

  ORDS.DEFINE_PARAMETER(
    p_module_name => 'modulos', p_pattern => '.', p_method => 'GET',
    p_name => 'X-APEX-STATUS-CODE', p_bind_variable_name => 'status_code',
    p_source_type => 'HEADER', p_param_type => 'INT', p_access_method => 'OUT');

  ----------------------------------------------------------------------------
  -- POST /modulos/  · alta
  ----------------------------------------------------------------------------
  ORDS.DEFINE_HANDLER(
    p_module_name => 'modulos',
    p_pattern     => '.',
    p_method      => 'POST',
    p_source_type => ORDS.source_type_plsql,
    p_source      => q'~
DECLARE
  l_sesion NUMBER;
  l_id     NUMBER;
BEGIN
  l_sesion := PKG_TOKENS.VALIDAR_TOKEN(REPLACE(:authorization, 'Bearer ', ''));
  IF l_sesion IS NULL THEN
    :status_code := 401;
    :resultado := '{"error":"Sesion invalida o vencida"}';
    RETURN;
  END IF;

  -- Tocar el catalogo cambia lo que ve todo el mundo: solo administradores.
  IF NOT PKG_PERMISOS.ES_ADMIN(l_sesion) THEN
    :status_code := 403;
    :resultado := '{"error":"Requiere permisos de administrador"}';
    RETURN;
  END IF;

  PKG_PERMISOS.CREAR_MODULO(
    p_codigo    => :codigo,
    p_nombre    => :nombre,
    p_icono     => :icono,
    p_orden     => TO_NUMBER(:orden),
    p_id_modulo => l_id
  );
  COMMIT;

  :status_code := 201;
  :resultado := JSON_OBJECT('id' VALUE l_id, 'ok' VALUE 'true');
EXCEPTION
  WHEN OTHERS THEN
    ROLLBACK;
    IF SQLCODE BETWEEN -20004 AND -20001 THEN
      :status_code := 400;
      :resultado := JSON_OBJECT('error' VALUE SUBSTR(SQLERRM, 12));
    ELSE
      :status_code := 500;
      :resultado := '{"error":"Error al crear el modulo"}';
    END IF;
END;
~'
  );

  ORDS.DEFINE_PARAMETER(
    p_module_name => 'modulos', p_pattern => '.', p_method => 'POST',
    p_name => 'authorization', p_bind_variable_name => 'authorization',
    p_source_type => 'HEADER', p_param_type => 'STRING', p_access_method => 'IN');

  ORDS.DEFINE_PARAMETER(
    p_module_name => 'modulos', p_pattern => '.', p_method => 'POST',
    p_name => 'resultado', p_bind_variable_name => 'resultado',
    p_source_type => 'RESPONSE', p_param_type => 'STRING', p_access_method => 'OUT');

  ORDS.DEFINE_PARAMETER(
    p_module_name => 'modulos', p_pattern => '.', p_method => 'POST',
    p_name => 'X-APEX-STATUS-CODE', p_bind_variable_name => 'status_code',
    p_source_type => 'HEADER', p_param_type => 'INT', p_access_method => 'OUT');

  ----------------------------------------------------------------------------
  -- PUT /modulos/:id  · modificación
  ----------------------------------------------------------------------------
  ORDS.DEFINE_TEMPLATE(p_module_name => 'modulos', p_pattern => ':id');

  ORDS.DEFINE_HANDLER(
    p_module_name => 'modulos',
    p_pattern     => ':id',
    p_method      => 'PUT',
    p_source_type => ORDS.source_type_plsql,
    p_source      => q'~
DECLARE
  l_sesion NUMBER;
BEGIN
  l_sesion := PKG_TOKENS.VALIDAR_TOKEN(REPLACE(:authorization, 'Bearer ', ''));
  IF l_sesion IS NULL THEN
    :status_code := 401;
    :resultado := '{"error":"Sesion invalida o vencida"}';
    RETURN;
  END IF;

  IF NOT PKG_PERMISOS.ES_ADMIN(l_sesion) THEN
    :status_code := 403;
    :resultado := '{"error":"Requiere permisos de administrador"}';
    RETURN;
  END IF;

  -- NULL = "no cambiar" en todos los opcionales, asi que un PUT parcial no
  -- pisa lo que no manda. NULLIF(..., '') porque un parametro ausente llega
  -- como cadena vacia, no como NULL, y TO_NUMBER('') es ORA-01722.
  PKG_PERMISOS.ACTUALIZAR_MODULO(
    p_id_modulo => TO_NUMBER(:id),
    p_nombre    => :nombre,
    p_icono     => :icono,
    p_orden     => TO_NUMBER(NULLIF(:orden, '')),
    p_activo    => NULLIF(:activo, '')
  );
  COMMIT;

  :status_code := 200;
  :resultado := '{"ok":true}';
EXCEPTION
  WHEN OTHERS THEN
    ROLLBACK;
    IF SQLCODE = -20002 THEN
      :status_code := 404;
      :resultado := '{"error":"El modulo no existe"}';
    ELSIF SQLCODE BETWEEN -20004 AND -20001 THEN
      :status_code := 400;
      :resultado := JSON_OBJECT('error' VALUE SUBSTR(SQLERRM, 12));
    ELSE
      :status_code := 500;
      :resultado := '{"error":"Error al actualizar el modulo"}';
    END IF;
END;
~'
  );

  ORDS.DEFINE_PARAMETER(
    p_module_name => 'modulos', p_pattern => ':id', p_method => 'PUT',
    p_name => 'authorization', p_bind_variable_name => 'authorization',
    p_source_type => 'HEADER', p_param_type => 'STRING', p_access_method => 'IN');

  ORDS.DEFINE_PARAMETER(
    p_module_name => 'modulos', p_pattern => ':id', p_method => 'PUT',
    p_name => 'resultado', p_bind_variable_name => 'resultado',
    p_source_type => 'RESPONSE', p_param_type => 'STRING', p_access_method => 'OUT');

  ORDS.DEFINE_PARAMETER(
    p_module_name => 'modulos', p_pattern => ':id', p_method => 'PUT',
    p_name => 'X-APEX-STATUS-CODE', p_bind_variable_name => 'status_code',
    p_source_type => 'HEADER', p_param_type => 'INT', p_access_method => 'OUT');

  ----------------------------------------------------------------------------
  -- DELETE /modulos/:id  · baja
  ----------------------------------------------------------------------------
  ORDS.DEFINE_HANDLER(
    p_module_name => 'modulos',
    p_pattern     => ':id',
    p_method      => 'DELETE',
    p_source_type => ORDS.source_type_plsql,
    p_source      => q'~
DECLARE
  l_sesion NUMBER;
BEGIN
  l_sesion := PKG_TOKENS.VALIDAR_TOKEN(REPLACE(:authorization, 'Bearer ', ''));
  IF l_sesion IS NULL THEN
    :status_code := 401;
    :resultado := '{"error":"Sesion invalida o vencida"}';
    RETURN;
  END IF;

  IF NOT PKG_PERMISOS.ES_ADMIN(l_sesion) THEN
    :status_code := 403;
    :resultado := '{"error":"Requiere permisos de administrador"}';
    RETURN;
  END IF;

  PKG_PERMISOS.ELIMINAR_MODULO(TO_NUMBER(:id));
  COMMIT;

  :status_code := 200;
  :resultado := '{"ok":true}';
EXCEPTION
  WHEN OTHERS THEN
    ROLLBACK;
    IF SQLCODE = -20002 THEN
      :status_code := 404;
      :resultado := '{"error":"El modulo no existe"}';
    ELSIF SQLCODE BETWEEN -20004 AND -20001 THEN
      :status_code := 400;
      :resultado := JSON_OBJECT('error' VALUE SUBSTR(SQLERRM, 12));
    ELSE
      :status_code := 500;
      :resultado := '{"error":"Error al eliminar el modulo"}';
    END IF;
END;
~'
  );

  ORDS.DEFINE_PARAMETER(
    p_module_name => 'modulos', p_pattern => ':id', p_method => 'DELETE',
    p_name => 'authorization', p_bind_variable_name => 'authorization',
    p_source_type => 'HEADER', p_param_type => 'STRING', p_access_method => 'IN');

  ORDS.DEFINE_PARAMETER(
    p_module_name => 'modulos', p_pattern => ':id', p_method => 'DELETE',
    p_name => 'resultado', p_bind_variable_name => 'resultado',
    p_source_type => 'RESPONSE', p_param_type => 'STRING', p_access_method => 'OUT');

  ORDS.DEFINE_PARAMETER(
    p_module_name => 'modulos', p_pattern => ':id', p_method => 'DELETE',
    p_name => 'X-APEX-STATUS-CODE', p_bind_variable_name => 'status_code',
    p_source_type => 'HEADER', p_param_type => 'INT', p_access_method => 'OUT');

  COMMIT;
END;
/

--------------------------------------------------------------------------------
-- 3. ORDS · MÓDULO /paginas/   (requieren token)
--
--   GET    /paginas/       listado (opcionalmente filtrado por módulo)
--   POST   /paginas/       alta
--   PUT    /paginas/:id    modificación
--   DELETE /paginas/:id    baja
--------------------------------------------------------------------------------

BEGIN
  BORRAR_MODULO_ORDS('paginas');

  ORDS.DEFINE_MODULE(
    p_module_name    => 'paginas',
    p_base_path      => '/paginas/',
    p_items_per_page => 0,
    p_status         => 'PUBLISHED',
    p_comments       => 'Catalogo de paginas (requiere token)'
  );

  ----------------------------------------------------------------------------
  -- GET /paginas/  · listado, filtrable por módulo
  ----------------------------------------------------------------------------
  ORDS.DEFINE_TEMPLATE(p_module_name => 'paginas', p_pattern => '.');

  ORDS.DEFINE_HANDLER(
    p_module_name => 'paginas',
    p_pattern     => '.',
    p_method      => 'GET',
    p_source_type => ORDS.source_type_plsql,
    p_source      => q'~
DECLARE
  l_sesion NUMBER;
  l_items  CLOB;
BEGIN
  l_sesion := PKG_TOKENS.VALIDAR_TOKEN(REPLACE(:authorization, 'Bearer ', ''));
  IF l_sesion IS NULL THEN
    :status_code := 401;
    :resultado := '{"error":"Sesion invalida o vencida"}';
    RETURN;
  END IF;

  SELECT JSON_ARRAYAGG(
           JSON_OBJECT(
             'id'           VALUE p.ID_PAGINA,
             'idModulo'     VALUE p.ID_MODULO,
             'moduloCodigo' VALUE m.CODIGO,
             'moduloNombre' VALUE m.NOMBRE,
             'codigo'       VALUE p.CODIGO,
             'nombre'       VALUE p.NOMBRE,
             'ruta'         VALUE p.RUTA,
             'orden'        VALUE p.ORDEN,
             -- 'A'/'I' tal cual la columna, sin traducir a numeros.
             'activo'       VALUE UPPER(TRIM(p.ACTIVO))
             RETURNING CLOB
           ) ORDER BY m.ORDEN, p.ORDEN, p.NOMBRE RETURNING CLOB
         )
    INTO l_items
    FROM PAGINAS p
    JOIN MODULOS m ON m.ID_MODULO = p.ID_MODULO
   WHERE (:idModulo IS NULL OR p.ID_MODULO = TO_NUMBER(:idModulo));

  :status_code := 200;
  :resultado := JSON_OBJECT('items' VALUE NVL(l_items, TO_CLOB('[]')) FORMAT JSON
                            RETURNING CLOB);
EXCEPTION
  WHEN OTHERS THEN
    APEX_DEBUG.ERROR('paginas GET: ' || SQLERRM || ' | ' ||
                     DBMS_UTILITY.FORMAT_ERROR_BACKTRACE);
    :status_code := 500;
    :resultado := '{"error":"Error al listar paginas"}';
END;
~'
  );

  ORDS.DEFINE_PARAMETER(
    p_module_name => 'paginas', p_pattern => '.', p_method => 'GET',
    p_name => 'authorization', p_bind_variable_name => 'authorization',
    p_source_type => 'HEADER', p_param_type => 'STRING', p_access_method => 'IN');

  ORDS.DEFINE_PARAMETER(
    p_module_name => 'paginas', p_pattern => '.', p_method => 'GET',
    p_name => 'resultado', p_bind_variable_name => 'resultado',
    p_source_type => 'RESPONSE', p_param_type => 'STRING', p_access_method => 'OUT');

  ORDS.DEFINE_PARAMETER(
    p_module_name => 'paginas', p_pattern => '.', p_method => 'GET',
    p_name => 'X-APEX-STATUS-CODE', p_bind_variable_name => 'status_code',
    p_source_type => 'HEADER', p_param_type => 'INT', p_access_method => 'OUT');

  ----------------------------------------------------------------------------
  -- POST /paginas/  · alta
  ----------------------------------------------------------------------------
  ORDS.DEFINE_HANDLER(
    p_module_name => 'paginas',
    p_pattern     => '.',
    p_method      => 'POST',
    p_source_type => ORDS.source_type_plsql,
    p_source      => q'~
DECLARE
  l_sesion NUMBER;
  l_id     NUMBER;
BEGIN
  l_sesion := PKG_TOKENS.VALIDAR_TOKEN(REPLACE(:authorization, 'Bearer ', ''));
  IF l_sesion IS NULL THEN
    :status_code := 401;
    :resultado := '{"error":"Sesion invalida o vencida"}';
    RETURN;
  END IF;

  IF NOT PKG_PERMISOS.ES_ADMIN(l_sesion) THEN
    :status_code := 403;
    :resultado := '{"error":"Requiere permisos de administrador"}';
    RETURN;
  END IF;

  PKG_PERMISOS.CREAR_PAGINA(
    p_id_modulo => TO_NUMBER(:idModulo),
    p_codigo    => :codigo,
    p_nombre    => :nombre,
    p_ruta      => :ruta,
    p_orden     => TO_NUMBER(:orden),
    p_id_pagina => l_id
  );
  COMMIT;

  :status_code := 201;
  :resultado := JSON_OBJECT('id' VALUE l_id, 'ok' VALUE 'true');
EXCEPTION
  WHEN OTHERS THEN
    ROLLBACK;
    IF SQLCODE = -20002 THEN
      :status_code := 404;
      :resultado := '{"error":"El modulo no existe"}';
    ELSIF SQLCODE BETWEEN -20004 AND -20001 THEN
      :status_code := 400;
      :resultado := JSON_OBJECT('error' VALUE SUBSTR(SQLERRM, 12));
    ELSE
      :status_code := 500;
      :resultado := '{"error":"Error al crear la pagina"}';
    END IF;
END;
~'
  );

  ORDS.DEFINE_PARAMETER(
    p_module_name => 'paginas', p_pattern => '.', p_method => 'POST',
    p_name => 'authorization', p_bind_variable_name => 'authorization',
    p_source_type => 'HEADER', p_param_type => 'STRING', p_access_method => 'IN');

  ORDS.DEFINE_PARAMETER(
    p_module_name => 'paginas', p_pattern => '.', p_method => 'POST',
    p_name => 'resultado', p_bind_variable_name => 'resultado',
    p_source_type => 'RESPONSE', p_param_type => 'STRING', p_access_method => 'OUT');

  ORDS.DEFINE_PARAMETER(
    p_module_name => 'paginas', p_pattern => '.', p_method => 'POST',
    p_name => 'X-APEX-STATUS-CODE', p_bind_variable_name => 'status_code',
    p_source_type => 'HEADER', p_param_type => 'INT', p_access_method => 'OUT');

  ----------------------------------------------------------------------------
  -- PUT /paginas/:id  · modificación
  ----------------------------------------------------------------------------
  ORDS.DEFINE_TEMPLATE(p_module_name => 'paginas', p_pattern => ':id');

  ORDS.DEFINE_HANDLER(
    p_module_name => 'paginas',
    p_pattern     => ':id',
    p_method      => 'PUT',
    p_source_type => ORDS.source_type_plsql,
    p_source      => q'~
DECLARE
  l_sesion NUMBER;
BEGIN
  l_sesion := PKG_TOKENS.VALIDAR_TOKEN(REPLACE(:authorization, 'Bearer ', ''));
  IF l_sesion IS NULL THEN
    :status_code := 401;
    :resultado := '{"error":"Sesion invalida o vencida"}';
    RETURN;
  END IF;

  IF NOT PKG_PERMISOS.ES_ADMIN(l_sesion) THEN
    :status_code := 403;
    :resultado := '{"error":"Requiere permisos de administrador"}';
    RETURN;
  END IF;

  -- Mismo criterio que ACTUALIZAR_MODULO: NULL = "no cambiar" y NULLIF para
  -- que un parametro ausente no muera en TO_NUMBER('').
  PKG_PERMISOS.ACTUALIZAR_PAGINA(
    p_id_pagina => TO_NUMBER(:id),
    p_id_modulo => TO_NUMBER(NULLIF(:idModulo, '')),
    p_nombre    => :nombre,
    p_ruta      => :ruta,
    p_orden     => TO_NUMBER(NULLIF(:orden, '')),
    p_activo    => NULLIF(:activo, '')
  );
  COMMIT;

  :status_code := 200;
  :resultado := '{"ok":true}';
EXCEPTION
  WHEN OTHERS THEN
    ROLLBACK;
    IF SQLCODE = -20002 THEN
      :status_code := 404;
      :resultado := '{"error":"La pagina no existe"}';
    ELSIF SQLCODE BETWEEN -20004 AND -20001 THEN
      :status_code := 400;
      :resultado := JSON_OBJECT('error' VALUE SUBSTR(SQLERRM, 12));
    ELSE
      :status_code := 500;
      :resultado := '{"error":"Error al actualizar la pagina"}';
    END IF;
END;
~'
  );

  ORDS.DEFINE_PARAMETER(
    p_module_name => 'paginas', p_pattern => ':id', p_method => 'PUT',
    p_name => 'authorization', p_bind_variable_name => 'authorization',
    p_source_type => 'HEADER', p_param_type => 'STRING', p_access_method => 'IN');

  ORDS.DEFINE_PARAMETER(
    p_module_name => 'paginas', p_pattern => ':id', p_method => 'PUT',
    p_name => 'resultado', p_bind_variable_name => 'resultado',
    p_source_type => 'RESPONSE', p_param_type => 'STRING', p_access_method => 'OUT');

  ORDS.DEFINE_PARAMETER(
    p_module_name => 'paginas', p_pattern => ':id', p_method => 'PUT',
    p_name => 'X-APEX-STATUS-CODE', p_bind_variable_name => 'status_code',
    p_source_type => 'HEADER', p_param_type => 'INT', p_access_method => 'OUT');

  ----------------------------------------------------------------------------
  -- DELETE /paginas/:id  · baja
  ----------------------------------------------------------------------------
  ORDS.DEFINE_HANDLER(
    p_module_name => 'paginas',
    p_pattern     => ':id',
    p_method      => 'DELETE',
    p_source_type => ORDS.source_type_plsql,
    p_source      => q'~
DECLARE
  l_sesion NUMBER;
BEGIN
  l_sesion := PKG_TOKENS.VALIDAR_TOKEN(REPLACE(:authorization, 'Bearer ', ''));
  IF l_sesion IS NULL THEN
    :status_code := 401;
    :resultado := '{"error":"Sesion invalida o vencida"}';
    RETURN;
  END IF;

  IF NOT PKG_PERMISOS.ES_ADMIN(l_sesion) THEN
    :status_code := 403;
    :resultado := '{"error":"Requiere permisos de administrador"}';
    RETURN;
  END IF;

  PKG_PERMISOS.ELIMINAR_PAGINA(TO_NUMBER(:id));
  COMMIT;

  :status_code := 200;
  :resultado := '{"ok":true}';
EXCEPTION
  WHEN OTHERS THEN
    ROLLBACK;
    IF SQLCODE = -20002 THEN
      :status_code := 404;
      :resultado := '{"error":"La pagina no existe"}';
    ELSE
      :status_code := 500;
      :resultado := '{"error":"Error al eliminar la pagina"}';
    END IF;
END;
~'
  );

  ORDS.DEFINE_PARAMETER(
    p_module_name => 'paginas', p_pattern => ':id', p_method => 'DELETE',
    p_name => 'authorization', p_bind_variable_name => 'authorization',
    p_source_type => 'HEADER', p_param_type => 'STRING', p_access_method => 'IN');

  ORDS.DEFINE_PARAMETER(
    p_module_name => 'paginas', p_pattern => ':id', p_method => 'DELETE',
    p_name => 'resultado', p_bind_variable_name => 'resultado',
    p_source_type => 'RESPONSE', p_param_type => 'STRING', p_access_method => 'OUT');

  ORDS.DEFINE_PARAMETER(
    p_module_name => 'paginas', p_pattern => ':id', p_method => 'DELETE',
    p_name => 'X-APEX-STATUS-CODE', p_bind_variable_name => 'status_code',
    p_source_type => 'HEADER', p_param_type => 'INT', p_access_method => 'OUT');

  COMMIT;
END;
/

--------------------------------------------------------------------------------
-- 4. ORDS · MÓDULO /permisos/   (requieren token)
--
--   GET  /permisos/mi-menu          menú del usuario logueado
--   GET  /permisos/usuario/:id      qué páginas tiene asignadas un usuario
--   PUT  /permisos/usuario/:id      reemplaza sus permisos
--------------------------------------------------------------------------------

BEGIN
  BORRAR_MODULO_ORDS('permisos');

  ORDS.DEFINE_MODULE(
    p_module_name    => 'permisos',
    p_base_path      => '/permisos/',
    p_items_per_page => 0,
    p_status         => 'PUBLISHED',
    p_comments       => 'Permisos de acceso por usuario (requiere token)'
  );

  ----------------------------------------------------------------------------
  -- GET /permisos/mi-menu  · lo que el usuario actual puede ver
  --
  -- Devuelve solo los módulos con al menos una página permitida, y dentro de
  -- cada uno solo esas páginas. Es lo que dibuja el menú lateral.
  ----------------------------------------------------------------------------
  ORDS.DEFINE_TEMPLATE(p_module_name => 'permisos', p_pattern => 'mi-menu');

  ORDS.DEFINE_HANDLER(
    p_module_name => 'permisos',
    p_pattern     => 'mi-menu',
    p_method      => 'GET',
    p_source_type => ORDS.source_type_plsql,
    p_source      => q'~
DECLARE
  l_sesion NUMBER;
  l_admin  NUMBER := 0;
  l_items  CLOB;
BEGIN
  l_sesion := PKG_TOKENS.VALIDAR_TOKEN(REPLACE(:authorization, 'Bearer ', ''));
  IF l_sesion IS NULL THEN
    :status_code := 401;
    :resultado := '{"error":"Sesion invalida o vencida"}';
    RETURN;
  END IF;

  IF PKG_PERMISOS.ES_ADMIN(l_sesion) THEN
    l_admin := 1;
  END IF;

  -- El admin ve el catalogo completo; el resto, solo lo asignado. La
  -- condicion l_admin = 1 corta el filtro por USUARIO_PAGINAS.
  SELECT JSON_ARRAYAGG(
           JSON_OBJECT(
             'id'      VALUE m.ID_MODULO,
             'codigo'  VALUE m.CODIGO,
             'nombre'  VALUE m.NOMBRE,
             'icono'   VALUE m.ICONO,
             'orden'   VALUE m.ORDEN,
             'paginas' VALUE (
               SELECT JSON_ARRAYAGG(
                        JSON_OBJECT(
                          'id'     VALUE p.ID_PAGINA,
                          'codigo' VALUE p.CODIGO,
                          'nombre' VALUE p.NOMBRE,
                          'ruta'   VALUE p.RUTA,
                          'orden'  VALUE p.ORDEN
                          RETURNING CLOB
                        ) ORDER BY p.ORDEN, p.NOMBRE RETURNING CLOB
                      )
                 FROM PAGINAS p
                WHERE p.ID_MODULO = m.ID_MODULO
                  AND UPPER(TRIM(p.ACTIVO)) = 'A'
                  AND (l_admin = 1
                       OR EXISTS (SELECT 1
                                    FROM USUARIO_PAGINAS up
                                   WHERE up.ID_PAGINA  = p.ID_PAGINA
                                     AND up.ID_USUARIO = l_sesion))
             ) FORMAT JSON
             RETURNING CLOB
           ) ORDER BY m.ORDEN, m.NOMBRE RETURNING CLOB
         )
    INTO l_items
    FROM MODULOS m
   WHERE UPPER(TRIM(m.ACTIVO)) = 'A'
     -- Un modulo sin paginas visibles no se muestra: seria un menu que no
     -- lleva a ninguna parte.
     AND EXISTS (SELECT 1
                   FROM PAGINAS p
                  WHERE p.ID_MODULO = m.ID_MODULO
                    AND UPPER(TRIM(p.ACTIVO)) = 'A'
                    AND (l_admin = 1
                         OR EXISTS (SELECT 1
                                      FROM USUARIO_PAGINAS up
                                     WHERE up.ID_PAGINA  = p.ID_PAGINA
                                       AND up.ID_USUARIO = l_sesion)));

  :status_code := 200;
  :resultado := JSON_OBJECT(
    'esAdmin' VALUE l_admin,
    'modulos' VALUE NVL(l_items, TO_CLOB('[]')) FORMAT JSON
    RETURNING CLOB
  );
EXCEPTION
  WHEN OTHERS THEN
    APEX_DEBUG.ERROR('permisos mi-menu: ' || SQLERRM || ' | ' ||
                     DBMS_UTILITY.FORMAT_ERROR_BACKTRACE);
    :status_code := 500;
    :resultado := '{"error":"Error al obtener el menu"}';
END;
~'
  );

  ORDS.DEFINE_PARAMETER(
    p_module_name => 'permisos', p_pattern => 'mi-menu', p_method => 'GET',
    p_name => 'authorization', p_bind_variable_name => 'authorization',
    p_source_type => 'HEADER', p_param_type => 'STRING', p_access_method => 'IN');

  ORDS.DEFINE_PARAMETER(
    p_module_name => 'permisos', p_pattern => 'mi-menu', p_method => 'GET',
    p_name => 'resultado', p_bind_variable_name => 'resultado',
    p_source_type => 'RESPONSE', p_param_type => 'STRING', p_access_method => 'OUT');

  ORDS.DEFINE_PARAMETER(
    p_module_name => 'permisos', p_pattern => 'mi-menu', p_method => 'GET',
    p_name => 'X-APEX-STATUS-CODE', p_bind_variable_name => 'status_code',
    p_source_type => 'HEADER', p_param_type => 'INT', p_access_method => 'OUT');

  ----------------------------------------------------------------------------
  -- GET /permisos/usuario/:id  · qué tiene asignado un usuario
  ----------------------------------------------------------------------------
  ORDS.DEFINE_TEMPLATE(p_module_name => 'permisos', p_pattern => 'usuario/:id');

  ORDS.DEFINE_HANDLER(
    p_module_name => 'permisos',
    p_pattern     => 'usuario/:id',
    p_method      => 'GET',
    p_source_type => ORDS.source_type_plsql,
    p_source      => q'~
DECLARE
  l_sesion NUMBER;
  l_ids    CLOB;
  l_admin  NUMBER := 0;
BEGIN
  l_sesion := PKG_TOKENS.VALIDAR_TOKEN(REPLACE(:authorization, 'Bearer ', ''));
  IF l_sesion IS NULL THEN
    :status_code := 401;
    :resultado := '{"error":"Sesion invalida o vencida"}';
    RETURN;
  END IF;

  -- Ver los permisos de OTRO usuario es cosa de administradores; los propios
  -- los puede consultar cualquiera.
  IF NOT PKG_PERMISOS.ES_ADMIN(l_sesion) AND l_sesion != TO_NUMBER(:id) THEN
    :status_code := 403;
    :resultado := '{"error":"Requiere permisos de administrador"}';
    RETURN;
  END IF;

  SELECT CASE WHEN UPPER(TRIM(ES_ADMIN)) = 'S' THEN 1 ELSE 0 END
    INTO l_admin
    FROM USUARIOS
   WHERE ID_USUARIO = TO_NUMBER(:id);

  SELECT JSON_ARRAYAGG(ID_PAGINA ORDER BY ID_PAGINA RETURNING CLOB)
    INTO l_ids
    FROM USUARIO_PAGINAS
   WHERE ID_USUARIO = TO_NUMBER(:id);

  :status_code := 200;
  :resultado := JSON_OBJECT(
    'idUsuario'  VALUE TO_NUMBER(:id),
    'esAdmin'    VALUE l_admin,
    'idsPaginas' VALUE NVL(l_ids, TO_CLOB('[]')) FORMAT JSON
    RETURNING CLOB
  );
EXCEPTION
  WHEN NO_DATA_FOUND THEN
    :status_code := 404;
    :resultado := '{"error":"El usuario no existe"}';
  WHEN OTHERS THEN
    APEX_DEBUG.ERROR('permisos usuario GET: ' || SQLERRM || ' | ' ||
                     DBMS_UTILITY.FORMAT_ERROR_BACKTRACE);
    :status_code := 500;
    :resultado := '{"error":"Error al obtener los permisos"}';
END;
~'
  );

  ORDS.DEFINE_PARAMETER(
    p_module_name => 'permisos', p_pattern => 'usuario/:id', p_method => 'GET',
    p_name => 'authorization', p_bind_variable_name => 'authorization',
    p_source_type => 'HEADER', p_param_type => 'STRING', p_access_method => 'IN');

  ORDS.DEFINE_PARAMETER(
    p_module_name => 'permisos', p_pattern => 'usuario/:id', p_method => 'GET',
    p_name => 'resultado', p_bind_variable_name => 'resultado',
    p_source_type => 'RESPONSE', p_param_type => 'STRING', p_access_method => 'OUT');

  ORDS.DEFINE_PARAMETER(
    p_module_name => 'permisos', p_pattern => 'usuario/:id', p_method => 'GET',
    p_name => 'X-APEX-STATUS-CODE', p_bind_variable_name => 'status_code',
    p_source_type => 'HEADER', p_param_type => 'INT', p_access_method => 'OUT');

  ----------------------------------------------------------------------------
  -- PUT /permisos/usuario/:id  · reemplaza los permisos del usuario
  --
  -- Body: { "idsPaginas": "1,2,5" }  ("" deja al usuario sin acceso a nada)
  ----------------------------------------------------------------------------
  ORDS.DEFINE_HANDLER(
    p_module_name => 'permisos',
    p_pattern     => 'usuario/:id',
    p_method      => 'PUT',
    p_source_type => ORDS.source_type_plsql,
    p_source      => q'~
DECLARE
  l_sesion NUMBER;
BEGIN
  l_sesion := PKG_TOKENS.VALIDAR_TOKEN(REPLACE(:authorization, 'Bearer ', ''));
  IF l_sesion IS NULL THEN
    :status_code := 401;
    :resultado := '{"error":"Sesion invalida o vencida"}';
    RETURN;
  END IF;

  IF NOT PKG_PERMISOS.ES_ADMIN(l_sesion) THEN
    :status_code := 403;
    :resultado := '{"error":"Requiere permisos de administrador"}';
    RETURN;
  END IF;

  PKG_PERMISOS.REEMPLAZAR(TO_NUMBER(:id), :idsPaginas);
  COMMIT;

  :status_code := 200;
  :resultado := '{"ok":true}';
EXCEPTION
  WHEN OTHERS THEN
    ROLLBACK;
    IF SQLCODE = -20002 THEN
      :status_code := 404;
      :resultado := '{"error":"El usuario no existe"}';
    ELSIF SQLCODE BETWEEN -20004 AND -20001 THEN
      :status_code := 400;
      :resultado := JSON_OBJECT('error' VALUE SUBSTR(SQLERRM, 12));
    ELSE
      :status_code := 500;
      :resultado := '{"error":"Error al guardar los permisos"}';
    END IF;
END;
~'
  );

  ORDS.DEFINE_PARAMETER(
    p_module_name => 'permisos', p_pattern => 'usuario/:id', p_method => 'PUT',
    p_name => 'authorization', p_bind_variable_name => 'authorization',
    p_source_type => 'HEADER', p_param_type => 'STRING', p_access_method => 'IN');

  ORDS.DEFINE_PARAMETER(
    p_module_name => 'permisos', p_pattern => 'usuario/:id', p_method => 'PUT',
    p_name => 'resultado', p_bind_variable_name => 'resultado',
    p_source_type => 'RESPONSE', p_param_type => 'STRING', p_access_method => 'OUT');

  ORDS.DEFINE_PARAMETER(
    p_module_name => 'permisos', p_pattern => 'usuario/:id', p_method => 'PUT',
    p_name => 'X-APEX-STATUS-CODE', p_bind_variable_name => 'status_code',
    p_source_type => 'HEADER', p_param_type => 'INT', p_access_method => 'OUT');

  COMMIT;
END;
/

--------------------------------------------------------------------------------
-- 5. DATOS INICIALES
--
-- Carga el módulo Ventas con las páginas del ejemplo. Solo si la tabla está
-- vacía, para que reejecutar el script no duplique ni pise cambios hechos a
-- mano.
--
-- Los demás módulos (Compras, Stock, Tesorería, RRHH, Reportes) se agregan
-- por el endpoint o repitiendo este bloque: el catálogo es una tabla, sumar
-- filas no requiere tocar código.
--------------------------------------------------------------------------------

DECLARE
  l_existe    NUMBER;
  l_id_modulo NUMBER;
  l_id_pagina NUMBER;
BEGIN
  SELECT COUNT(*) INTO l_existe FROM MODULOS;

  IF l_existe > 0 THEN
    DBMS_OUTPUT.PUT_LINE('Ya hay modulos cargados: no se toca el catalogo.');
    RETURN;
  END IF;

  PKG_PERMISOS.CREAR_MODULO(
    p_codigo    => 'VENTAS',
    p_nombre    => 'Ventas',
    p_icono     => 'Tags',   -- nombre del icono en lucide-react
    p_orden     => 10,
    p_id_modulo => l_id_modulo
  );

  PKG_PERMISOS.CREAR_PAGINA(l_id_modulo, 'VENTAS_CLIENTES', 'Clientes',
                            '/ventas/clientes', 10, l_id_pagina);
  PKG_PERMISOS.CREAR_PAGINA(l_id_modulo, 'VENTAS_LIMITES', 'Limites de credito',
                            '/ventas/limites', 20, l_id_pagina);
  PKG_PERMISOS.CREAR_PAGINA(l_id_modulo, 'VENTAS_FACTURACION', 'Facturacion',
                            '/ventas/facturacion', 30, l_id_pagina);
  PKG_PERMISOS.CREAR_PAGINA(l_id_modulo, 'VENTAS_COBRANZAS', 'Cobranzas',
                            '/ventas/cobranzas', 40, l_id_pagina);

  COMMIT;
  DBMS_OUTPUT.PUT_LINE('Modulo Ventas creado con 4 paginas.');
END;
/

--------------------------------------------------------------------------------
-- 6. VERIFICACIÓN
--------------------------------------------------------------------------------

DECLARE
  l_errores NUMBER;
BEGIN
  SELECT COUNT(*) INTO l_errores
    FROM USER_ERRORS
   WHERE NAME = 'PKG_PERMISOS';

  IF l_errores = 0 THEN
    DBMS_OUTPUT.PUT_LINE('OK: PKG_PERMISOS compilado sin errores.');
  ELSE
    DBMS_OUTPUT.PUT_LINE('ATENCION: ' || l_errores || ' errores de compilacion.');
  END IF;
END;
/

-- La columna correcta de USER_OBJECTS es OBJECT_NAME (no NAME).
SELECT OBJECT_NAME, OBJECT_TYPE, STATUS
  FROM USER_OBJECTS
 WHERE OBJECT_TYPE IN ('PACKAGE', 'PACKAGE BODY')
   AND OBJECT_NAME = 'PKG_PERMISOS'
 ORDER BY OBJECT_TYPE;

SELECT NAME, LINE, POSITION, TEXT
  FROM USER_ERRORS
 WHERE NAME = 'PKG_PERMISOS'
 ORDER BY SEQUENCE;

-- Catálogo cargado.
SELECT m.CODIGO AS modulo, p.CODIGO AS pagina, p.RUTA, p.ORDEN
  FROM MODULOS m
  LEFT JOIN PAGINAS p ON p.ID_MODULO = m.ID_MODULO
 ORDER BY m.ORDEN, p.ORDEN;

-- Endpoints publicados.
SELECT m.NAME AS modulo, m.URI_PREFIX, t.URI_TEMPLATE, h.METHOD
  FROM USER_ORDS_MODULES m
  JOIN USER_ORDS_TEMPLATES t ON t.MODULE_ID = m.ID
  JOIN USER_ORDS_HANDLERS  h ON h.TEMPLATE_ID = t.ID
 WHERE m.NAME IN ('modulos', 'paginas', 'permisos')
 ORDER BY m.NAME, t.URI_TEMPLATE, h.METHOD;

--------------------------------------------------------------------------------
-- 7. PRUEBA DEL CIRCUITO DE PERMISOS
--
-- Ejercita otorgar, consultar y revocar sin salir de la base. Si esto imprime
-- OK, el problema (si queda alguno) está en ORDS o en el cliente, no en el
-- paquete.
--
-- No deja rastro: todo lo que hace se revierte al final.
--------------------------------------------------------------------------------

DECLARE
  l_id_usuario NUMBER;
  l_id_pagina  NUMBER;
  l_ruta       VARCHAR2(150);
BEGIN
  DBMS_OUTPUT.PUT_LINE('--- Prueba de permisos ---');

  BEGIN
    SELECT ID_USUARIO INTO l_id_usuario FROM USUARIOS WHERE USUARIO = 'admin';
  EXCEPTION
    WHEN NO_DATA_FOUND THEN
      DBMS_OUTPUT.PUT_LINE('FALLA: no existe el usuario admin.');
      RETURN;
  END;

  BEGIN
    SELECT ID_PAGINA, RUTA INTO l_id_pagina, l_ruta
      FROM PAGINAS WHERE CODIGO = 'VENTAS_CLIENTES';
  EXCEPTION
    WHEN NO_DATA_FOUND THEN
      DBMS_OUTPUT.PUT_LINE('FALLA: no se cargo el catalogo de paginas.');
      RETURN;
  END;

  -- 1. El admin entra a todo sin permisos explícitos.
  IF PKG_PERMISOS.PUEDE_ACCEDER(l_id_usuario, l_ruta) THEN
    DBMS_OUTPUT.PUT_LINE('OK 1/4: el admin accede sin filas en USUARIO_PAGINAS.');
  ELSE
    DBMS_OUTPUT.PUT_LINE('FALLA: el admin no accede. Revisa USUARIOS.ES_ADMIN.');
    RETURN;
  END IF;

  -- 2. Otorgar es idempotente.
  PKG_PERMISOS.OTORGAR(l_id_usuario, l_id_pagina);
  PKG_PERMISOS.OTORGAR(l_id_usuario, l_id_pagina);
  DBMS_OUTPUT.PUT_LINE('OK 2/4: otorgar dos veces no duplica ni falla.');

  -- 3. Reemplazar deja exactamente lo indicado.
  PKG_PERMISOS.REEMPLAZAR(l_id_usuario, TO_CHAR(l_id_pagina));
  SELECT COUNT(*) INTO l_id_pagina
    FROM USUARIO_PAGINAS WHERE ID_USUARIO = l_id_usuario;

  IF l_id_pagina = 1 THEN
    DBMS_OUTPUT.PUT_LINE('OK 3/4: REEMPLAZAR dejo exactamente 1 permiso.');
  ELSE
    DBMS_OUTPUT.PUT_LINE('FALLA: quedaron ' || l_id_pagina || ' permisos, se esperaba 1.');
  END IF;

  -- 4. Reemplazar con lista vacía deja al usuario sin nada.
  PKG_PERMISOS.REEMPLAZAR(l_id_usuario, NULL);
  SELECT COUNT(*) INTO l_id_pagina
    FROM USUARIO_PAGINAS WHERE ID_USUARIO = l_id_usuario;

  IF l_id_pagina = 0 THEN
    DBMS_OUTPUT.PUT_LINE('OK 4/4: REEMPLAZAR con lista vacia revoca todo.');
    DBMS_OUTPUT.PUT_LINE('>>> El paquete de permisos funciona. <<<');
  ELSE
    DBMS_OUTPUT.PUT_LINE('FALLA: quedaron ' || l_id_pagina || ' permisos.');
  END IF;

  -- La prueba no debe dejar permisos puestos.
  ROLLBACK;
  DBMS_OUTPUT.PUT_LINE('(Cambios de la prueba revertidos.)');

EXCEPTION
  WHEN OTHERS THEN
    ROLLBACK;
    DBMS_OUTPUT.PUT_LINE('EXCEPCION: ' || SQLERRM);
    DBMS_OUTPUT.PUT_LINE(DBMS_UTILITY.FORMAT_ERROR_BACKTRACE);
END;
/
