/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AuthAdministracionRouteImport } from './routes/_auth.administracion'
import { Route as AuthArticulosRouteImport } from './routes/_auth.articulos'
import { Route as AuthArticulosUbicacionesRouteImport } from './routes/_auth.articulos-ubicaciones'
import { Route as AuthAsistenciasRouteImport } from './routes/_auth.asistencias'
import { Route as AuthBancosRouteImport } from './routes/_auth.bancos'
import { Route as AuthCanalesPagosRouteImport } from './routes/_auth.canales-pagos'
import { Route as AuthCategoriasRouteImport } from './routes/_auth.categorias'
import { Route as AuthCiudadesRouteImport } from './routes/_auth.ciudades'
import { Route as AuthCobrosRouteImport } from './routes/_auth.cobros'
import { Route as AuthCondicionesPagoRouteImport } from './routes/_auth.condiciones-pago'
import { Route as AuthConfiguracionRouteImport } from './routes/_auth.configuracion'
import { Route as AuthCuentasBancariasRouteImport } from './routes/_auth.cuentas-bancarias'
import { Route as AuthDepartamentosRouteImport } from './routes/_auth.departamentos'
import { Route as AuthEmpresasRouteImport } from './routes/_auth.empresas'
import { Route as AuthExistenciasRouteImport } from './routes/_auth.existencias'
import { Route as AuthFacturasComprasRouteImport } from './routes/_auth.facturas-compras'
import { Route as AuthHomeRouteImport } from './routes/_auth.home'
import { Route as AuthInstitucionesRouteImport } from './routes/_auth.instituciones'
import { Route as AuthInventariosRouteImport } from './routes/_auth.inventarios'
import { Route as AuthIvaRouteImport } from './routes/_auth.iva'
import { Route as AuthListasDescuentosRouteImport } from './routes/_auth.listas-descuentos'
import { Route as AuthMarcasRouteImport } from './routes/_auth.marcas'
import { Route as AuthMenuRouteImport } from './routes/_auth.menu'
import { Route as AuthMonedasRouteImport } from './routes/_auth.monedas'
import { Route as AuthPagosRouteImport } from './routes/_auth.pagos'
import { Route as AuthPaisesRouteImport } from './routes/_auth.paises'
import { Route as AuthPersonasRouteImport } from './routes/_auth.personas'
import { Route as AuthProfesoresRouteImport } from './routes/_auth.profesores'
import { Route as AuthPuntoVentaRouteImport } from './routes/_auth.punto-venta'
import { Route as AuthSucursalesRouteImport } from './routes/_auth.sucursales'
import { Route as AuthTalonariosRouteImport } from './routes/_auth.talonarios'
import { Route as AuthUbicacionesRouteImport } from './routes/_auth.ubicaciones'
import { Route as AuthUnidadesMedidaRouteImport } from './routes/_auth.unidades-medida'
import { Route as AuthVentasRouteImport } from './routes/_auth.ventas'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthAdministracionRoute = AuthAdministracionRouteImport.update({
  id: '/administracion',
  path: '/administracion',
  getParentRoute: () => AuthRoute,
} as any)
const AuthArticulosRoute = AuthArticulosRouteImport.update({
  id: '/articulos',
  path: '/articulos',
  getParentRoute: () => AuthRoute,
} as any)
const AuthArticulosUbicacionesRoute =
  AuthArticulosUbicacionesRouteImport.update({
    id: '/articulos-ubicaciones',
    path: '/articulos-ubicaciones',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthAsistenciasRoute = AuthAsistenciasRouteImport.update({
  id: '/asistencias',
  path: '/asistencias',
  getParentRoute: () => AuthRoute,
} as any)
const AuthBancosRoute = AuthBancosRouteImport.update({
  id: '/bancos',
  path: '/bancos',
  getParentRoute: () => AuthRoute,
} as any)
const AuthCanalesPagosRoute = AuthCanalesPagosRouteImport.update({
  id: '/canales-pagos',
  path: '/canales-pagos',
  getParentRoute: () => AuthRoute,
} as any)
const AuthCategoriasRoute = AuthCategoriasRouteImport.update({
  id: '/categorias',
  path: '/categorias',
  getParentRoute: () => AuthRoute,
} as any)
const AuthCiudadesRoute = AuthCiudadesRouteImport.update({
  id: '/ciudades',
  path: '/ciudades',
  getParentRoute: () => AuthRoute,
} as any)
const AuthCobrosRoute = AuthCobrosRouteImport.update({
  id: '/cobros',
  path: '/cobros',
  getParentRoute: () => AuthRoute,
} as any)
const AuthCondicionesPagoRoute = AuthCondicionesPagoRouteImport.update({
  id: '/condiciones-pago',
  path: '/condiciones-pago',
  getParentRoute: () => AuthRoute,
} as any)
const AuthConfiguracionRoute = AuthConfiguracionRouteImport.update({
  id: '/configuracion',
  path: '/configuracion',
  getParentRoute: () => AuthRoute,
} as any)
const AuthCuentasBancariasRoute = AuthCuentasBancariasRouteImport.update({
  id: '/cuentas-bancarias',
  path: '/cuentas-bancarias',
  getParentRoute: () => AuthRoute,
} as any)
const AuthDepartamentosRoute = AuthDepartamentosRouteImport.update({
  id: '/departamentos',
  path: '/departamentos',
  getParentRoute: () => AuthRoute,
} as any)
const AuthEmpresasRoute = AuthEmpresasRouteImport.update({
  id: '/empresas',
  path: '/empresas',
  getParentRoute: () => AuthRoute,
} as any)
const AuthExistenciasRoute = AuthExistenciasRouteImport.update({
  id: '/existencias',
  path: '/existencias',
  getParentRoute: () => AuthRoute,
} as any)
const AuthFacturasComprasRoute = AuthFacturasComprasRouteImport.update({
  id: '/facturas-compras',
  path: '/facturas-compras',
  getParentRoute: () => AuthRoute,
} as any)
const AuthHomeRoute = AuthHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthRoute,
} as any)
const AuthInstitucionesRoute = AuthInstitucionesRouteImport.update({
  id: '/instituciones',
  path: '/instituciones',
  getParentRoute: () => AuthRoute,
} as any)
const AuthInventariosRoute = AuthInventariosRouteImport.update({
  id: '/inventarios',
  path: '/inventarios',
  getParentRoute: () => AuthRoute,
} as any)
const AuthIvaRoute = AuthIvaRouteImport.update({
  id: '/iva',
  path: '/iva',
  getParentRoute: () => AuthRoute,
} as any)
const AuthListasDescuentosRoute = AuthListasDescuentosRouteImport.update({
  id: '/listas-descuentos',
  path: '/listas-descuentos',
  getParentRoute: () => AuthRoute,
} as any)
const AuthMarcasRoute = AuthMarcasRouteImport.update({
  id: '/marcas',
  path: '/marcas',
  getParentRoute: () => AuthRoute,
} as any)
const AuthMenuRoute = AuthMenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => AuthRoute,
} as any)
const AuthMonedasRoute = AuthMonedasRouteImport.update({
  id: '/monedas',
  path: '/monedas',
  getParentRoute: () => AuthRoute,
} as any)
const AuthPagosRoute = AuthPagosRouteImport.update({
  id: '/pagos',
  path: '/pagos',
  getParentRoute: () => AuthRoute,
} as any)
const AuthPaisesRoute = AuthPaisesRouteImport.update({
  id: '/paises',
  path: '/paises',
  getParentRoute: () => AuthRoute,
} as any)
const AuthPersonasRoute = AuthPersonasRouteImport.update({
  id: '/personas',
  path: '/personas',
  getParentRoute: () => AuthRoute,
} as any)
const AuthProfesoresRoute = AuthProfesoresRouteImport.update({
  id: '/profesores',
  path: '/profesores',
  getParentRoute: () => AuthRoute,
} as any)
const AuthPuntoVentaRoute = AuthPuntoVentaRouteImport.update({
  id: '/punto-venta',
  path: '/punto-venta',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSucursalesRoute = AuthSucursalesRouteImport.update({
  id: '/sucursales',
  path: '/sucursales',
  getParentRoute: () => AuthRoute,
} as any)
const AuthTalonariosRoute = AuthTalonariosRouteImport.update({
  id: '/talonarios',
  path: '/talonarios',
  getParentRoute: () => AuthRoute,
} as any)
const AuthUbicacionesRoute = AuthUbicacionesRouteImport.update({
  id: '/ubicaciones',
  path: '/ubicaciones',
  getParentRoute: () => AuthRoute,
} as any)
const AuthUnidadesMedidaRoute = AuthUnidadesMedidaRouteImport.update({
  id: '/unidades-medida',
  path: '/unidades-medida',
  getParentRoute: () => AuthRoute,
} as any)
const AuthVentasRoute = AuthVentasRouteImport.update({
  id: '/ventas',
  path: '/ventas',
  getParentRoute: () => AuthRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/administracion': typeof AuthAdministracionRoute
  '/articulos': typeof AuthArticulosRoute
  '/articulos-ubicaciones': typeof AuthArticulosUbicacionesRoute
  '/asistencias': typeof AuthAsistenciasRoute
  '/bancos': typeof AuthBancosRoute
  '/canales-pagos': typeof AuthCanalesPagosRoute
  '/categorias': typeof AuthCategoriasRoute
  '/ciudades': typeof AuthCiudadesRoute
  '/cobros': typeof AuthCobrosRoute
  '/condiciones-pago': typeof AuthCondicionesPagoRoute
  '/configuracion': typeof AuthConfiguracionRoute
  '/cuentas-bancarias': typeof AuthCuentasBancariasRoute
  '/departamentos': typeof AuthDepartamentosRoute
  '/empresas': typeof AuthEmpresasRoute
  '/existencias': typeof AuthExistenciasRoute
  '/facturas-compras': typeof AuthFacturasComprasRoute
  '/home': typeof AuthHomeRoute
  '/instituciones': typeof AuthInstitucionesRoute
  '/inventarios': typeof AuthInventariosRoute
  '/iva': typeof AuthIvaRoute
  '/listas-descuentos': typeof AuthListasDescuentosRoute
  '/marcas': typeof AuthMarcasRoute
  '/menu': typeof AuthMenuRoute
  '/monedas': typeof AuthMonedasRoute
  '/pagos': typeof AuthPagosRoute
  '/paises': typeof AuthPaisesRoute
  '/personas': typeof AuthPersonasRoute
  '/profesores': typeof AuthProfesoresRoute
  '/punto-venta': typeof AuthPuntoVentaRoute
  '/sucursales': typeof AuthSucursalesRoute
  '/talonarios': typeof AuthTalonariosRoute
  '/ubicaciones': typeof AuthUbicacionesRoute
  '/unidades-medida': typeof AuthUnidadesMedidaRoute
  '/ventas': typeof AuthVentasRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/administracion': typeof AuthAdministracionRoute
  '/articulos': typeof AuthArticulosRoute
  '/articulos-ubicaciones': typeof AuthArticulosUbicacionesRoute
  '/asistencias': typeof AuthAsistenciasRoute
  '/bancos': typeof AuthBancosRoute
  '/canales-pagos': typeof AuthCanalesPagosRoute
  '/categorias': typeof AuthCategoriasRoute
  '/ciudades': typeof AuthCiudadesRoute
  '/cobros': typeof AuthCobrosRoute
  '/condiciones-pago': typeof AuthCondicionesPagoRoute
  '/configuracion': typeof AuthConfiguracionRoute
  '/cuentas-bancarias': typeof AuthCuentasBancariasRoute
  '/departamentos': typeof AuthDepartamentosRoute
  '/empresas': typeof AuthEmpresasRoute
  '/existencias': typeof AuthExistenciasRoute
  '/facturas-compras': typeof AuthFacturasComprasRoute
  '/home': typeof AuthHomeRoute
  '/instituciones': typeof AuthInstitucionesRoute
  '/inventarios': typeof AuthInventariosRoute
  '/iva': typeof AuthIvaRoute
  '/listas-descuentos': typeof AuthListasDescuentosRoute
  '/marcas': typeof AuthMarcasRoute
  '/menu': typeof AuthMenuRoute
  '/monedas': typeof AuthMonedasRoute
  '/pagos': typeof AuthPagosRoute
  '/paises': typeof AuthPaisesRoute
  '/personas': typeof AuthPersonasRoute
  '/profesores': typeof AuthProfesoresRoute
  '/punto-venta': typeof AuthPuntoVentaRoute
  '/sucursales': typeof AuthSucursalesRoute
  '/talonarios': typeof AuthTalonariosRoute
  '/ubicaciones': typeof AuthUbicacionesRoute
  '/unidades-medida': typeof AuthUnidadesMedidaRoute
  '/ventas': typeof AuthVentasRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/_auth/administracion': typeof AuthAdministracionRoute
  '/_auth/articulos': typeof AuthArticulosRoute
  '/_auth/articulos-ubicaciones': typeof AuthArticulosUbicacionesRoute
  '/_auth/asistencias': typeof AuthAsistenciasRoute
  '/_auth/bancos': typeof AuthBancosRoute
  '/_auth/canales-pagos': typeof AuthCanalesPagosRoute
  '/_auth/categorias': typeof AuthCategoriasRoute
  '/_auth/ciudades': typeof AuthCiudadesRoute
  '/_auth/cobros': typeof AuthCobrosRoute
  '/_auth/condiciones-pago': typeof AuthCondicionesPagoRoute
  '/_auth/configuracion': typeof AuthConfiguracionRoute
  '/_auth/cuentas-bancarias': typeof AuthCuentasBancariasRoute
  '/_auth/departamentos': typeof AuthDepartamentosRoute
  '/_auth/empresas': typeof AuthEmpresasRoute
  '/_auth/existencias': typeof AuthExistenciasRoute
  '/_auth/facturas-compras': typeof AuthFacturasComprasRoute
  '/_auth/home': typeof AuthHomeRoute
  '/_auth/instituciones': typeof AuthInstitucionesRoute
  '/_auth/inventarios': typeof AuthInventariosRoute
  '/_auth/iva': typeof AuthIvaRoute
  '/_auth/listas-descuentos': typeof AuthListasDescuentosRoute
  '/_auth/marcas': typeof AuthMarcasRoute
  '/_auth/menu': typeof AuthMenuRoute
  '/_auth/monedas': typeof AuthMonedasRoute
  '/_auth/pagos': typeof AuthPagosRoute
  '/_auth/paises': typeof AuthPaisesRoute
  '/_auth/personas': typeof AuthPersonasRoute
  '/_auth/profesores': typeof AuthProfesoresRoute
  '/_auth/punto-venta': typeof AuthPuntoVentaRoute
  '/_auth/sucursales': typeof AuthSucursalesRoute
  '/_auth/talonarios': typeof AuthTalonariosRoute
  '/_auth/ubicaciones': typeof AuthUbicacionesRoute
  '/_auth/unidades-medida': typeof AuthUnidadesMedidaRoute
  '/_auth/ventas': typeof AuthVentasRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/administracion'
    | '/articulos'
    | '/articulos-ubicaciones'
    | '/asistencias'
    | '/bancos'
    | '/canales-pagos'
    | '/categorias'
    | '/ciudades'
    | '/cobros'
    | '/condiciones-pago'
    | '/configuracion'
    | '/cuentas-bancarias'
    | '/departamentos'
    | '/empresas'
    | '/existencias'
    | '/facturas-compras'
    | '/home'
    | '/instituciones'
    | '/inventarios'
    | '/iva'
    | '/listas-descuentos'
    | '/marcas'
    | '/menu'
    | '/monedas'
    | '/pagos'
    | '/paises'
    | '/personas'
    | '/profesores'
    | '/punto-venta'
    | '/sucursales'
    | '/talonarios'
    | '/ubicaciones'
    | '/unidades-medida'
    | '/ventas'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/administracion'
    | '/articulos'
    | '/articulos-ubicaciones'
    | '/asistencias'
    | '/bancos'
    | '/canales-pagos'
    | '/categorias'
    | '/ciudades'
    | '/cobros'
    | '/condiciones-pago'
    | '/configuracion'
    | '/cuentas-bancarias'
    | '/departamentos'
    | '/empresas'
    | '/existencias'
    | '/facturas-compras'
    | '/home'
    | '/instituciones'
    | '/inventarios'
    | '/iva'
    | '/listas-descuentos'
    | '/marcas'
    | '/menu'
    | '/monedas'
    | '/pagos'
    | '/paises'
    | '/personas'
    | '/profesores'
    | '/punto-venta'
    | '/sucursales'
    | '/talonarios'
    | '/ubicaciones'
    | '/unidades-medida'
    | '/ventas'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_auth/administracion'
    | '/_auth/articulos'
    | '/_auth/articulos-ubicaciones'
    | '/_auth/asistencias'
    | '/_auth/bancos'
    | '/_auth/canales-pagos'
    | '/_auth/categorias'
    | '/_auth/ciudades'
    | '/_auth/cobros'
    | '/_auth/condiciones-pago'
    | '/_auth/configuracion'
    | '/_auth/cuentas-bancarias'
    | '/_auth/departamentos'
    | '/_auth/empresas'
    | '/_auth/existencias'
    | '/_auth/facturas-compras'
    | '/_auth/home'
    | '/_auth/instituciones'
    | '/_auth/inventarios'
    | '/_auth/iva'
    | '/_auth/listas-descuentos'
    | '/_auth/marcas'
    | '/_auth/menu'
    | '/_auth/monedas'
    | '/_auth/pagos'
    | '/_auth/paises'
    | '/_auth/personas'
    | '/_auth/profesores'
    | '/_auth/punto-venta'
    | '/_auth/sucursales'
    | '/_auth/talonarios'
    | '/_auth/ubicaciones'
    | '/_auth/unidades-medida'
    | '/_auth/ventas'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/administracion': {
      id: '/_auth/administracion'
      path: '/administracion'
      fullPath: '/administracion'
      preLoaderRoute: typeof AuthAdministracionRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/articulos': {
      id: '/_auth/articulos'
      path: '/articulos'
      fullPath: '/articulos'
      preLoaderRoute: typeof AuthArticulosRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/articulos-ubicaciones': {
      id: '/_auth/articulos-ubicaciones'
      path: '/articulos-ubicaciones'
      fullPath: '/articulos-ubicaciones'
      preLoaderRoute: typeof AuthArticulosUbicacionesRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/asistencias': {
      id: '/_auth/asistencias'
      path: '/asistencias'
      fullPath: '/asistencias'
      preLoaderRoute: typeof AuthAsistenciasRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/bancos': {
      id: '/_auth/bancos'
      path: '/bancos'
      fullPath: '/bancos'
      preLoaderRoute: typeof AuthBancosRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/canales-pagos': {
      id: '/_auth/canales-pagos'
      path: '/canales-pagos'
      fullPath: '/canales-pagos'
      preLoaderRoute: typeof AuthCanalesPagosRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/categorias': {
      id: '/_auth/categorias'
      path: '/categorias'
      fullPath: '/categorias'
      preLoaderRoute: typeof AuthCategoriasRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/ciudades': {
      id: '/_auth/ciudades'
      path: '/ciudades'
      fullPath: '/ciudades'
      preLoaderRoute: typeof AuthCiudadesRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/cobros': {
      id: '/_auth/cobros'
      path: '/cobros'
      fullPath: '/cobros'
      preLoaderRoute: typeof AuthCobrosRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/condiciones-pago': {
      id: '/_auth/condiciones-pago'
      path: '/condiciones-pago'
      fullPath: '/condiciones-pago'
      preLoaderRoute: typeof AuthCondicionesPagoRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/configuracion': {
      id: '/_auth/configuracion'
      path: '/configuracion'
      fullPath: '/configuracion'
      preLoaderRoute: typeof AuthConfiguracionRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/cuentas-bancarias': {
      id: '/_auth/cuentas-bancarias'
      path: '/cuentas-bancarias'
      fullPath: '/cuentas-bancarias'
      preLoaderRoute: typeof AuthCuentasBancariasRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/departamentos': {
      id: '/_auth/departamentos'
      path: '/departamentos'
      fullPath: '/departamentos'
      preLoaderRoute: typeof AuthDepartamentosRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/empresas': {
      id: '/_auth/empresas'
      path: '/empresas'
      fullPath: '/empresas'
      preLoaderRoute: typeof AuthEmpresasRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/existencias': {
      id: '/_auth/existencias'
      path: '/existencias'
      fullPath: '/existencias'
      preLoaderRoute: typeof AuthExistenciasRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/facturas-compras': {
      id: '/_auth/facturas-compras'
      path: '/facturas-compras'
      fullPath: '/facturas-compras'
      preLoaderRoute: typeof AuthFacturasComprasRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/home': {
      id: '/_auth/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthHomeRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/instituciones': {
      id: '/_auth/instituciones'
      path: '/instituciones'
      fullPath: '/instituciones'
      preLoaderRoute: typeof AuthInstitucionesRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/inventarios': {
      id: '/_auth/inventarios'
      path: '/inventarios'
      fullPath: '/inventarios'
      preLoaderRoute: typeof AuthInventariosRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/iva': {
      id: '/_auth/iva'
      path: '/iva'
      fullPath: '/iva'
      preLoaderRoute: typeof AuthIvaRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/listas-descuentos': {
      id: '/_auth/listas-descuentos'
      path: '/listas-descuentos'
      fullPath: '/listas-descuentos'
      preLoaderRoute: typeof AuthListasDescuentosRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/marcas': {
      id: '/_auth/marcas'
      path: '/marcas'
      fullPath: '/marcas'
      preLoaderRoute: typeof AuthMarcasRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/menu': {
      id: '/_auth/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof AuthMenuRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/monedas': {
      id: '/_auth/monedas'
      path: '/monedas'
      fullPath: '/monedas'
      preLoaderRoute: typeof AuthMonedasRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/pagos': {
      id: '/_auth/pagos'
      path: '/pagos'
      fullPath: '/pagos'
      preLoaderRoute: typeof AuthPagosRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/paises': {
      id: '/_auth/paises'
      path: '/paises'
      fullPath: '/paises'
      preLoaderRoute: typeof AuthPaisesRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/personas': {
      id: '/_auth/personas'
      path: '/personas'
      fullPath: '/personas'
      preLoaderRoute: typeof AuthPersonasRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/profesores': {
      id: '/_auth/profesores'
      path: '/profesores'
      fullPath: '/profesores'
      preLoaderRoute: typeof AuthProfesoresRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/punto-venta': {
      id: '/_auth/punto-venta'
      path: '/punto-venta'
      fullPath: '/punto-venta'
      preLoaderRoute: typeof AuthPuntoVentaRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/sucursales': {
      id: '/_auth/sucursales'
      path: '/sucursales'
      fullPath: '/sucursales'
      preLoaderRoute: typeof AuthSucursalesRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/talonarios': {
      id: '/_auth/talonarios'
      path: '/talonarios'
      fullPath: '/talonarios'
      preLoaderRoute: typeof AuthTalonariosRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/ubicaciones': {
      id: '/_auth/ubicaciones'
      path: '/ubicaciones'
      fullPath: '/ubicaciones'
      preLoaderRoute: typeof AuthUbicacionesRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/unidades-medida': {
      id: '/_auth/unidades-medida'
      path: '/unidades-medida'
      fullPath: '/unidades-medida'
      preLoaderRoute: typeof AuthUnidadesMedidaRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/ventas': {
      id: '/_auth/ventas'
      path: '/ventas'
      fullPath: '/ventas'
      preLoaderRoute: typeof AuthVentasRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthRouteChildren {
  AuthAdministracionRoute: typeof AuthAdministracionRoute
  AuthArticulosRoute: typeof AuthArticulosRoute
  AuthArticulosUbicacionesRoute: typeof AuthArticulosUbicacionesRoute
  AuthAsistenciasRoute: typeof AuthAsistenciasRoute
  AuthBancosRoute: typeof AuthBancosRoute
  AuthCanalesPagosRoute: typeof AuthCanalesPagosRoute
  AuthCategoriasRoute: typeof AuthCategoriasRoute
  AuthCiudadesRoute: typeof AuthCiudadesRoute
  AuthCobrosRoute: typeof AuthCobrosRoute
  AuthCondicionesPagoRoute: typeof AuthCondicionesPagoRoute
  AuthConfiguracionRoute: typeof AuthConfiguracionRoute
  AuthCuentasBancariasRoute: typeof AuthCuentasBancariasRoute
  AuthDepartamentosRoute: typeof AuthDepartamentosRoute
  AuthEmpresasRoute: typeof AuthEmpresasRoute
  AuthExistenciasRoute: typeof AuthExistenciasRoute
  AuthFacturasComprasRoute: typeof AuthFacturasComprasRoute
  AuthHomeRoute: typeof AuthHomeRoute
  AuthInstitucionesRoute: typeof AuthInstitucionesRoute
  AuthInventariosRoute: typeof AuthInventariosRoute
  AuthIvaRoute: typeof AuthIvaRoute
  AuthListasDescuentosRoute: typeof AuthListasDescuentosRoute
  AuthMarcasRoute: typeof AuthMarcasRoute
  AuthMenuRoute: typeof AuthMenuRoute
  AuthMonedasRoute: typeof AuthMonedasRoute
  AuthPagosRoute: typeof AuthPagosRoute
  AuthPaisesRoute: typeof AuthPaisesRoute
  AuthPersonasRoute: typeof AuthPersonasRoute
  AuthProfesoresRoute: typeof AuthProfesoresRoute
  AuthPuntoVentaRoute: typeof AuthPuntoVentaRoute
  AuthSucursalesRoute: typeof AuthSucursalesRoute
  AuthTalonariosRoute: typeof AuthTalonariosRoute
  AuthUbicacionesRoute: typeof AuthUbicacionesRoute
  AuthUnidadesMedidaRoute: typeof AuthUnidadesMedidaRoute
  AuthVentasRoute: typeof AuthVentasRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthAdministracionRoute: AuthAdministracionRoute,
  AuthArticulosRoute: AuthArticulosRoute,
  AuthArticulosUbicacionesRoute: AuthArticulosUbicacionesRoute,
  AuthAsistenciasRoute: AuthAsistenciasRoute,
  AuthBancosRoute: AuthBancosRoute,
  AuthCanalesPagosRoute: AuthCanalesPagosRoute,
  AuthCategoriasRoute: AuthCategoriasRoute,
  AuthCiudadesRoute: AuthCiudadesRoute,
  AuthCobrosRoute: AuthCobrosRoute,
  AuthCondicionesPagoRoute: AuthCondicionesPagoRoute,
  AuthConfiguracionRoute: AuthConfiguracionRoute,
  AuthCuentasBancariasRoute: AuthCuentasBancariasRoute,
  AuthDepartamentosRoute: AuthDepartamentosRoute,
  AuthEmpresasRoute: AuthEmpresasRoute,
  AuthExistenciasRoute: AuthExistenciasRoute,
  AuthFacturasComprasRoute: AuthFacturasComprasRoute,
  AuthHomeRoute: AuthHomeRoute,
  AuthInstitucionesRoute: AuthInstitucionesRoute,
  AuthInventariosRoute: AuthInventariosRoute,
  AuthIvaRoute: AuthIvaRoute,
  AuthListasDescuentosRoute: AuthListasDescuentosRoute,
  AuthMarcasRoute: AuthMarcasRoute,
  AuthMenuRoute: AuthMenuRoute,
  AuthMonedasRoute: AuthMonedasRoute,
  AuthPagosRoute: AuthPagosRoute,
  AuthPaisesRoute: AuthPaisesRoute,
  AuthPersonasRoute: AuthPersonasRoute,
  AuthProfesoresRoute: AuthProfesoresRoute,
  AuthPuntoVentaRoute: AuthPuntoVentaRoute,
  AuthSucursalesRoute: AuthSucursalesRoute,
  AuthTalonariosRoute: AuthTalonariosRoute,
  AuthUbicacionesRoute: AuthUbicacionesRoute,
  AuthUnidadesMedidaRoute: AuthUnidadesMedidaRoute,
  AuthVentasRoute: AuthVentasRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
