/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AuthAdministracionRouteImport } from './routes/_auth.administracion'
import { Route as AuthArticulosRouteImport } from './routes/_auth.articulos'
import { Route as AuthArticulosUbicacionesRouteImport } from './routes/_auth.articulos-ubicaciones'
import { Route as AuthCategoriasRouteImport } from './routes/_auth.categorias'
import { Route as AuthCiudadesRouteImport } from './routes/_auth.ciudades'
import { Route as AuthCondicionesPagoRouteImport } from './routes/_auth.condiciones-pago'
import { Route as AuthConfiguracionRouteImport } from './routes/_auth.configuracion'
import { Route as AuthDepartamentosRouteImport } from './routes/_auth.departamentos'
import { Route as AuthEmpresasRouteImport } from './routes/_auth.empresas'
import { Route as AuthFacturasComprasRouteImport } from './routes/_auth.facturas-compras'
import { Route as AuthHomeRouteImport } from './routes/_auth.home'
import { Route as AuthInstitucionesRouteImport } from './routes/_auth.instituciones'
import { Route as AuthInventariosRouteImport } from './routes/_auth.inventarios'
import { Route as AuthIvaRouteImport } from './routes/_auth.iva'
import { Route as AuthListasDescuentosRouteImport } from './routes/_auth.listas-descuentos'
import { Route as AuthLotesRouteImport } from './routes/_auth.lotes'
import { Route as AuthMenuRouteImport } from './routes/_auth.menu'
import { Route as AuthMonedasRouteImport } from './routes/_auth.monedas'
import { Route as AuthPaisesRouteImport } from './routes/_auth.paises'
import { Route as AuthPersonasRouteImport } from './routes/_auth.personas'
import { Route as AuthSucursalesRouteImport } from './routes/_auth.sucursales'
import { Route as AuthUbicacionesRouteImport } from './routes/_auth.ubicaciones'
import { Route as AuthUnidadesMedidaRouteImport } from './routes/_auth.unidades-medida'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthAdministracionRoute = AuthAdministracionRouteImport.update({
  id: '/administracion',
  path: '/administracion',
  getParentRoute: () => AuthRoute,
} as any)
const AuthArticulosRoute = AuthArticulosRouteImport.update({
  id: '/articulos',
  path: '/articulos',
  getParentRoute: () => AuthRoute,
} as any)
const AuthArticulosUbicacionesRoute =
  AuthArticulosUbicacionesRouteImport.update({
    id: '/articulos-ubicaciones',
    path: '/articulos-ubicaciones',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthCategoriasRoute = AuthCategoriasRouteImport.update({
  id: '/categorias',
  path: '/categorias',
  getParentRoute: () => AuthRoute,
} as any)
const AuthCiudadesRoute = AuthCiudadesRouteImport.update({
  id: '/ciudades',
  path: '/ciudades',
  getParentRoute: () => AuthRoute,
} as any)
const AuthCondicionesPagoRoute = AuthCondicionesPagoRouteImport.update({
  id: '/condiciones-pago',
  path: '/condiciones-pago',
  getParentRoute: () => AuthRoute,
} as any)
const AuthConfiguracionRoute = AuthConfiguracionRouteImport.update({
  id: '/configuracion',
  path: '/configuracion',
  getParentRoute: () => AuthRoute,
} as any)
const AuthDepartamentosRoute = AuthDepartamentosRouteImport.update({
  id: '/departamentos',
  path: '/departamentos',
  getParentRoute: () => AuthRoute,
} as any)
const AuthEmpresasRoute = AuthEmpresasRouteImport.update({
  id: '/empresas',
  path: '/empresas',
  getParentRoute: () => AuthRoute,
} as any)
const AuthFacturasComprasRoute = AuthFacturasComprasRouteImport.update({
  id: '/facturas-compras',
  path: '/facturas-compras',
  getParentRoute: () => AuthRoute,
} as any)
const AuthHomeRoute = AuthHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthRoute,
} as any)
const AuthInstitucionesRoute = AuthInstitucionesRouteImport.update({
  id: '/instituciones',
  path: '/instituciones',
  getParentRoute: () => AuthRoute,
} as any)
const AuthInventariosRoute = AuthInventariosRouteImport.update({
  id: '/inventarios',
  path: '/inventarios',
  getParentRoute: () => AuthRoute,
} as any)
const AuthIvaRoute = AuthIvaRouteImport.update({
  id: '/iva',
  path: '/iva',
  getParentRoute: () => AuthRoute,
} as any)
const AuthListasDescuentosRoute = AuthListasDescuentosRouteImport.update({
  id: '/listas-descuentos',
  path: '/listas-descuentos',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLotesRoute = AuthLotesRouteImport.update({
  id: '/lotes',
  path: '/lotes',
  getParentRoute: () => AuthRoute,
} as any)
const AuthMenuRoute = AuthMenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => AuthRoute,
} as any)
const AuthMonedasRoute = AuthMonedasRouteImport.update({
  id: '/monedas',
  path: '/monedas',
  getParentRoute: () => AuthRoute,
} as any)
const AuthPaisesRoute = AuthPaisesRouteImport.update({
  id: '/paises',
  path: '/paises',
  getParentRoute: () => AuthRoute,
} as any)
const AuthPersonasRoute = AuthPersonasRouteImport.update({
  id: '/personas',
  path: '/personas',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSucursalesRoute = AuthSucursalesRouteImport.update({
  id: '/sucursales',
  path: '/sucursales',
  getParentRoute: () => AuthRoute,
} as any)
const AuthUbicacionesRoute = AuthUbicacionesRouteImport.update({
  id: '/ubicaciones',
  path: '/ubicaciones',
  getParentRoute: () => AuthRoute,
} as any)
const AuthUnidadesMedidaRoute = AuthUnidadesMedidaRouteImport.update({
  id: '/unidades-medida',
  path: '/unidades-medida',
  getParentRoute: () => AuthRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/administracion': typeof AuthAdministracionRoute
  '/articulos': typeof AuthArticulosRoute
  '/articulos-ubicaciones': typeof AuthArticulosUbicacionesRoute
  '/categorias': typeof AuthCategoriasRoute
  '/ciudades': typeof AuthCiudadesRoute
  '/condiciones-pago': typeof AuthCondicionesPagoRoute
  '/configuracion': typeof AuthConfiguracionRoute
  '/departamentos': typeof AuthDepartamentosRoute
  '/empresas': typeof AuthEmpresasRoute
  '/facturas-compras': typeof AuthFacturasComprasRoute
  '/home': typeof AuthHomeRoute
  '/instituciones': typeof AuthInstitucionesRoute
  '/inventarios': typeof AuthInventariosRoute
  '/iva': typeof AuthIvaRoute
  '/listas-descuentos': typeof AuthListasDescuentosRoute
  '/lotes': typeof AuthLotesRoute
  '/menu': typeof AuthMenuRoute
  '/monedas': typeof AuthMonedasRoute
  '/paises': typeof AuthPaisesRoute
  '/personas': typeof AuthPersonasRoute
  '/sucursales': typeof AuthSucursalesRoute
  '/ubicaciones': typeof AuthUbicacionesRoute
  '/unidades-medida': typeof AuthUnidadesMedidaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/administracion': typeof AuthAdministracionRoute
  '/articulos': typeof AuthArticulosRoute
  '/articulos-ubicaciones': typeof AuthArticulosUbicacionesRoute
  '/categorias': typeof AuthCategoriasRoute
  '/ciudades': typeof AuthCiudadesRoute
  '/condiciones-pago': typeof AuthCondicionesPagoRoute
  '/configuracion': typeof AuthConfiguracionRoute
  '/departamentos': typeof AuthDepartamentosRoute
  '/empresas': typeof AuthEmpresasRoute
  '/facturas-compras': typeof AuthFacturasComprasRoute
  '/home': typeof AuthHomeRoute
  '/instituciones': typeof AuthInstitucionesRoute
  '/inventarios': typeof AuthInventariosRoute
  '/iva': typeof AuthIvaRoute
  '/listas-descuentos': typeof AuthListasDescuentosRoute
  '/lotes': typeof AuthLotesRoute
  '/menu': typeof AuthMenuRoute
  '/monedas': typeof AuthMonedasRoute
  '/paises': typeof AuthPaisesRoute
  '/personas': typeof AuthPersonasRoute
  '/sucursales': typeof AuthSucursalesRoute
  '/ubicaciones': typeof AuthUbicacionesRoute
  '/unidades-medida': typeof AuthUnidadesMedidaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/_auth/administracion': typeof AuthAdministracionRoute
  '/_auth/articulos': typeof AuthArticulosRoute
  '/_auth/articulos-ubicaciones': typeof AuthArticulosUbicacionesRoute
  '/_auth/categorias': typeof AuthCategoriasRoute
  '/_auth/ciudades': typeof AuthCiudadesRoute
  '/_auth/condiciones-pago': typeof AuthCondicionesPagoRoute
  '/_auth/configuracion': typeof AuthConfiguracionRoute
  '/_auth/departamentos': typeof AuthDepartamentosRoute
  '/_auth/empresas': typeof AuthEmpresasRoute
  '/_auth/facturas-compras': typeof AuthFacturasComprasRoute
  '/_auth/home': typeof AuthHomeRoute
  '/_auth/instituciones': typeof AuthInstitucionesRoute
  '/_auth/inventarios': typeof AuthInventariosRoute
  '/_auth/iva': typeof AuthIvaRoute
  '/_auth/listas-descuentos': typeof AuthListasDescuentosRoute
  '/_auth/lotes': typeof AuthLotesRoute
  '/_auth/menu': typeof AuthMenuRoute
  '/_auth/monedas': typeof AuthMonedasRoute
  '/_auth/paises': typeof AuthPaisesRoute
  '/_auth/personas': typeof AuthPersonasRoute
  '/_auth/sucursales': typeof AuthSucursalesRoute
  '/_auth/ubicaciones': typeof AuthUbicacionesRoute
  '/_auth/unidades-medida': typeof AuthUnidadesMedidaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/administracion'
    | '/articulos'
    | '/articulos-ubicaciones'
    | '/categorias'
    | '/ciudades'
    | '/condiciones-pago'
    | '/configuracion'
    | '/departamentos'
    | '/empresas'
    | '/facturas-compras'
    | '/home'
    | '/instituciones'
    | '/inventarios'
    | '/iva'
    | '/listas-descuentos'
    | '/lotes'
    | '/menu'
    | '/monedas'
    | '/paises'
    | '/personas'
    | '/sucursales'
    | '/ubicaciones'
    | '/unidades-medida'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/administracion'
    | '/articulos'
    | '/articulos-ubicaciones'
    | '/categorias'
    | '/ciudades'
    | '/condiciones-pago'
    | '/configuracion'
    | '/departamentos'
    | '/empresas'
    | '/facturas-compras'
    | '/home'
    | '/instituciones'
    | '/inventarios'
    | '/iva'
    | '/listas-descuentos'
    | '/lotes'
    | '/menu'
    | '/monedas'
    | '/paises'
    | '/personas'
    | '/sucursales'
    | '/ubicaciones'
    | '/unidades-medida'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_auth/administracion'
    | '/_auth/articulos'
    | '/_auth/articulos-ubicaciones'
    | '/_auth/categorias'
    | '/_auth/ciudades'
    | '/_auth/condiciones-pago'
    | '/_auth/configuracion'
    | '/_auth/departamentos'
    | '/_auth/empresas'
    | '/_auth/facturas-compras'
    | '/_auth/home'
    | '/_auth/instituciones'
    | '/_auth/inventarios'
    | '/_auth/iva'
    | '/_auth/listas-descuentos'
    | '/_auth/lotes'
    | '/_auth/menu'
    | '/_auth/monedas'
    | '/_auth/paises'
    | '/_auth/personas'
    | '/_auth/sucursales'
    | '/_auth/ubicaciones'
    | '/_auth/unidades-medida'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/administracion': {
      id: '/_auth/administracion'
      path: '/administracion'
      fullPath: '/administracion'
      preLoaderRoute: typeof AuthAdministracionRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/articulos': {
      id: '/_auth/articulos'
      path: '/articulos'
      fullPath: '/articulos'
      preLoaderRoute: typeof AuthArticulosRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/articulos-ubicaciones': {
      id: '/_auth/articulos-ubicaciones'
      path: '/articulos-ubicaciones'
      fullPath: '/articulos-ubicaciones'
      preLoaderRoute: typeof AuthArticulosUbicacionesRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/categorias': {
      id: '/_auth/categorias'
      path: '/categorias'
      fullPath: '/categorias'
      preLoaderRoute: typeof AuthCategoriasRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/ciudades': {
      id: '/_auth/ciudades'
      path: '/ciudades'
      fullPath: '/ciudades'
      preLoaderRoute: typeof AuthCiudadesRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/condiciones-pago': {
      id: '/_auth/condiciones-pago'
      path: '/condiciones-pago'
      fullPath: '/condiciones-pago'
      preLoaderRoute: typeof AuthCondicionesPagoRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/configuracion': {
      id: '/_auth/configuracion'
      path: '/configuracion'
      fullPath: '/configuracion'
      preLoaderRoute: typeof AuthConfiguracionRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/departamentos': {
      id: '/_auth/departamentos'
      path: '/departamentos'
      fullPath: '/departamentos'
      preLoaderRoute: typeof AuthDepartamentosRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/empresas': {
      id: '/_auth/empresas'
      path: '/empresas'
      fullPath: '/empresas'
      preLoaderRoute: typeof AuthEmpresasRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/facturas-compras': {
      id: '/_auth/facturas-compras'
      path: '/facturas-compras'
      fullPath: '/facturas-compras'
      preLoaderRoute: typeof AuthFacturasComprasRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/home': {
      id: '/_auth/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthHomeRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/instituciones': {
      id: '/_auth/instituciones'
      path: '/instituciones'
      fullPath: '/instituciones'
      preLoaderRoute: typeof AuthInstitucionesRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/inventarios': {
      id: '/_auth/inventarios'
      path: '/inventarios'
      fullPath: '/inventarios'
      preLoaderRoute: typeof AuthInventariosRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/iva': {
      id: '/_auth/iva'
      path: '/iva'
      fullPath: '/iva'
      preLoaderRoute: typeof AuthIvaRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/listas-descuentos': {
      id: '/_auth/listas-descuentos'
      path: '/listas-descuentos'
      fullPath: '/listas-descuentos'
      preLoaderRoute: typeof AuthListasDescuentosRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/lotes': {
      id: '/_auth/lotes'
      path: '/lotes'
      fullPath: '/lotes'
      preLoaderRoute: typeof AuthLotesRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/menu': {
      id: '/_auth/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof AuthMenuRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/monedas': {
      id: '/_auth/monedas'
      path: '/monedas'
      fullPath: '/monedas'
      preLoaderRoute: typeof AuthMonedasRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/paises': {
      id: '/_auth/paises'
      path: '/paises'
      fullPath: '/paises'
      preLoaderRoute: typeof AuthPaisesRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/personas': {
      id: '/_auth/personas'
      path: '/personas'
      fullPath: '/personas'
      preLoaderRoute: typeof AuthPersonasRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/sucursales': {
      id: '/_auth/sucursales'
      path: '/sucursales'
      fullPath: '/sucursales'
      preLoaderRoute: typeof AuthSucursalesRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/ubicaciones': {
      id: '/_auth/ubicaciones'
      path: '/ubicaciones'
      fullPath: '/ubicaciones'
      preLoaderRoute: typeof AuthUbicacionesRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/unidades-medida': {
      id: '/_auth/unidades-medida'
      path: '/unidades-medida'
      fullPath: '/unidades-medida'
      preLoaderRoute: typeof AuthUnidadesMedidaRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthRouteChildren {
  AuthAdministracionRoute: typeof AuthAdministracionRoute
  AuthArticulosRoute: typeof AuthArticulosRoute
  AuthArticulosUbicacionesRoute: typeof AuthArticulosUbicacionesRoute
  AuthCategoriasRoute: typeof AuthCategoriasRoute
  AuthCiudadesRoute: typeof AuthCiudadesRoute
  AuthCondicionesPagoRoute: typeof AuthCondicionesPagoRoute
  AuthConfiguracionRoute: typeof AuthConfiguracionRoute
  AuthDepartamentosRoute: typeof AuthDepartamentosRoute
  AuthEmpresasRoute: typeof AuthEmpresasRoute
  AuthFacturasComprasRoute: typeof AuthFacturasComprasRoute
  AuthHomeRoute: typeof AuthHomeRoute
  AuthInstitucionesRoute: typeof AuthInstitucionesRoute
  AuthInventariosRoute: typeof AuthInventariosRoute
  AuthIvaRoute: typeof AuthIvaRoute
  AuthListasDescuentosRoute: typeof AuthListasDescuentosRoute
  AuthLotesRoute: typeof AuthLotesRoute
  AuthMenuRoute: typeof AuthMenuRoute
  AuthMonedasRoute: typeof AuthMonedasRoute
  AuthPaisesRoute: typeof AuthPaisesRoute
  AuthPersonasRoute: typeof AuthPersonasRoute
  AuthSucursalesRoute: typeof AuthSucursalesRoute
  AuthUbicacionesRoute: typeof AuthUbicacionesRoute
  AuthUnidadesMedidaRoute: typeof AuthUnidadesMedidaRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthAdministracionRoute: AuthAdministracionRoute,
  AuthArticulosRoute: AuthArticulosRoute,
  AuthArticulosUbicacionesRoute: AuthArticulosUbicacionesRoute,
  AuthCategoriasRoute: AuthCategoriasRoute,
  AuthCiudadesRoute: AuthCiudadesRoute,
  AuthCondicionesPagoRoute: AuthCondicionesPagoRoute,
  AuthConfiguracionRoute: AuthConfiguracionRoute,
  AuthDepartamentosRoute: AuthDepartamentosRoute,
  AuthEmpresasRoute: AuthEmpresasRoute,
  AuthFacturasComprasRoute: AuthFacturasComprasRoute,
  AuthHomeRoute: AuthHomeRoute,
  AuthInstitucionesRoute: AuthInstitucionesRoute,
  AuthInventariosRoute: AuthInventariosRoute,
  AuthIvaRoute: AuthIvaRoute,
  AuthListasDescuentosRoute: AuthListasDescuentosRoute,
  AuthLotesRoute: AuthLotesRoute,
  AuthMenuRoute: AuthMenuRoute,
  AuthMonedasRoute: AuthMonedasRoute,
  AuthPaisesRoute: AuthPaisesRoute,
  AuthPersonasRoute: AuthPersonasRoute,
  AuthSucursalesRoute: AuthSucursalesRoute,
  AuthUbicacionesRoute: AuthUbicacionesRoute,
  AuthUnidadesMedidaRoute: AuthUnidadesMedidaRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
