/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AuthAdministracionRouteImport } from './routes/_auth.administracion'
import { Route as AuthConfiguracionRouteImport } from './routes/_auth.configuracion'
import { Route as AuthDepartamentosRouteImport } from './routes/_auth.departamentos'
import { Route as AuthHomeRouteImport } from './routes/_auth.home'
import { Route as AuthMenuRouteImport } from './routes/_auth.menu'
import { Route as AuthPaisesRouteImport } from './routes/_auth.paises'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthAdministracionRoute = AuthAdministracionRouteImport.update({
  id: '/administracion',
  path: '/administracion',
  getParentRoute: () => AuthRoute,
} as any)
const AuthConfiguracionRoute = AuthConfiguracionRouteImport.update({
  id: '/configuracion',
  path: '/configuracion',
  getParentRoute: () => AuthRoute,
} as any)
const AuthDepartamentosRoute = AuthDepartamentosRouteImport.update({
  id: '/departamentos',
  path: '/departamentos',
  getParentRoute: () => AuthRoute,
} as any)
const AuthHomeRoute = AuthHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthRoute,
} as any)
const AuthMenuRoute = AuthMenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => AuthRoute,
} as any)
const AuthPaisesRoute = AuthPaisesRouteImport.update({
  id: '/paises',
  path: '/paises',
  getParentRoute: () => AuthRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/administracion': typeof AuthAdministracionRoute
  '/configuracion': typeof AuthConfiguracionRoute
  '/departamentos': typeof AuthDepartamentosRoute
  '/home': typeof AuthHomeRoute
  '/menu': typeof AuthMenuRoute
  '/paises': typeof AuthPaisesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/administracion': typeof AuthAdministracionRoute
  '/configuracion': typeof AuthConfiguracionRoute
  '/departamentos': typeof AuthDepartamentosRoute
  '/home': typeof AuthHomeRoute
  '/menu': typeof AuthMenuRoute
  '/paises': typeof AuthPaisesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/_auth/administracion': typeof AuthAdministracionRoute
  '/_auth/configuracion': typeof AuthConfiguracionRoute
  '/_auth/departamentos': typeof AuthDepartamentosRoute
  '/_auth/home': typeof AuthHomeRoute
  '/_auth/menu': typeof AuthMenuRoute
  '/_auth/paises': typeof AuthPaisesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/administracion'
    | '/configuracion'
    | '/departamentos'
    | '/home'
    | '/menu'
    | '/paises'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/administracion'
    | '/configuracion'
    | '/departamentos'
    | '/home'
    | '/menu'
    | '/paises'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_auth/administracion'
    | '/_auth/configuracion'
    | '/_auth/departamentos'
    | '/_auth/home'
    | '/_auth/menu'
    | '/_auth/paises'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/administracion': {
      id: '/_auth/administracion'
      path: '/administracion'
      fullPath: '/administracion'
      preLoaderRoute: typeof AuthAdministracionRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/configuracion': {
      id: '/_auth/configuracion'
      path: '/configuracion'
      fullPath: '/configuracion'
      preLoaderRoute: typeof AuthConfiguracionRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/departamentos': {
      id: '/_auth/departamentos'
      path: '/departamentos'
      fullPath: '/departamentos'
      preLoaderRoute: typeof AuthDepartamentosRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/home': {
      id: '/_auth/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthHomeRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/menu': {
      id: '/_auth/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof AuthMenuRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/paises': {
      id: '/_auth/paises'
      path: '/paises'
      fullPath: '/paises'
      preLoaderRoute: typeof AuthPaisesRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthRouteChildren {
  AuthAdministracionRoute: typeof AuthAdministracionRoute
  AuthConfiguracionRoute: typeof AuthConfiguracionRoute
  AuthDepartamentosRoute: typeof AuthDepartamentosRoute
  AuthHomeRoute: typeof AuthHomeRoute
  AuthMenuRoute: typeof AuthMenuRoute
  AuthPaisesRoute: typeof AuthPaisesRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthAdministracionRoute: AuthAdministracionRoute,
  AuthConfiguracionRoute: AuthConfiguracionRoute,
  AuthDepartamentosRoute: AuthDepartamentosRoute,
  AuthHomeRoute: AuthHomeRoute,
  AuthMenuRoute: AuthMenuRoute,
  AuthPaisesRoute: AuthPaisesRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
